/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FluentValidationResultsValidationFailure } from '../models';
// @ts-ignore
import { WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult } from '../models';
/**
 * WordTutorialSubtitleAdministrationApi - axios parameter creator
 * @export
 */
export const WordTutorialSubtitleAdministrationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Kelime eğitimine ait yeni bir çeviri dosyası yüklenmesini sağlar.
         * @param {File} [file] 
         * @param {number} [wordTutorialId] 
         * @param {string} [subtitleLanguageCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSubtitleToWordTutorial: async (file?: File, wordTutorialId?: number, subtitleLanguageCode?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/WordTutorialSubtitleAdministration/AddSubtitleToWordTutorial`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            if (wordTutorialId !== undefined) {
                localVarQueryParameter['WordTutorialId'] = wordTutorialId;
            }

            if (subtitleLanguageCode !== undefined) {
                localVarQueryParameter['SubtitleLanguageCode'] = subtitleLanguageCode;
            }


            if (file !== undefined) { 
                localVarFormParams.append('File', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Kelime eğitiminden bir altyazı dosyasının silinmesini sağlar.
         * @param {number} [subtitleId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeSubtitleFromWordTutorial: async (subtitleId?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/WordTutorialSubtitleAdministration/RemoveSubtitleFromWordTutorial`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (subtitleId !== undefined) {
                localVarQueryParameter['SubtitleId'] = subtitleId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WordTutorialSubtitleAdministrationApi - functional programming interface
 * @export
 */
export const WordTutorialSubtitleAdministrationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WordTutorialSubtitleAdministrationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Kelime eğitimine ait yeni bir çeviri dosyası yüklenmesini sağlar.
         * @param {File} [file] 
         * @param {number} [wordTutorialId] 
         * @param {string} [subtitleLanguageCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addSubtitleToWordTutorial(file?: File, wordTutorialId?: number, subtitleLanguageCode?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addSubtitleToWordTutorial(file, wordTutorialId, subtitleLanguageCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Kelime eğitiminden bir altyazı dosyasının silinmesini sağlar.
         * @param {number} [subtitleId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeSubtitleFromWordTutorial(subtitleId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeSubtitleFromWordTutorial(subtitleId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * WordTutorialSubtitleAdministrationApi - factory interface
 * @export
 */
export const WordTutorialSubtitleAdministrationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WordTutorialSubtitleAdministrationApiFp(configuration)
    return {
        /**
         * 
         * @summary Kelime eğitimine ait yeni bir çeviri dosyası yüklenmesini sağlar.
         * @param {File} [file] 
         * @param {number} [wordTutorialId] 
         * @param {string} [subtitleLanguageCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSubtitleToWordTutorial(file?: File, wordTutorialId?: number, subtitleLanguageCode?: string, options?: any): AxiosPromise<WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult> {
            return localVarFp.addSubtitleToWordTutorial(file, wordTutorialId, subtitleLanguageCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Kelime eğitiminden bir altyazı dosyasının silinmesini sağlar.
         * @param {number} [subtitleId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeSubtitleFromWordTutorial(subtitleId?: number, options?: any): AxiosPromise<object> {
            return localVarFp.removeSubtitleFromWordTutorial(subtitleId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WordTutorialSubtitleAdministrationApi - interface
 * @export
 * @interface WordTutorialSubtitleAdministrationApi
 */
export interface WordTutorialSubtitleAdministrationApiInterface {
    /**
     * 
     * @summary Kelime eğitimine ait yeni bir çeviri dosyası yüklenmesini sağlar.
     * @param {File} [file] 
     * @param {number} [wordTutorialId] 
     * @param {string} [subtitleLanguageCode] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialSubtitleAdministrationApiInterface
     */
    addSubtitleToWordTutorial(file?: File, wordTutorialId?: number, subtitleLanguageCode?: string, options?: AxiosRequestConfig): AxiosPromise<WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult>;

    /**
     * 
     * @summary Kelime eğitiminden bir altyazı dosyasının silinmesini sağlar.
     * @param {number} [subtitleId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialSubtitleAdministrationApiInterface
     */
    removeSubtitleFromWordTutorial(subtitleId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;

}

/**
 * WordTutorialSubtitleAdministrationApi - object-oriented interface
 * @export
 * @class WordTutorialSubtitleAdministrationApi
 * @extends {BaseAPI}
 */
export class WordTutorialSubtitleAdministrationApi extends BaseAPI implements WordTutorialSubtitleAdministrationApiInterface {
    /**
     * 
     * @summary Kelime eğitimine ait yeni bir çeviri dosyası yüklenmesini sağlar.
     * @param {File} [file] 
     * @param {number} [wordTutorialId] 
     * @param {string} [subtitleLanguageCode] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialSubtitleAdministrationApi
     */
    public addSubtitleToWordTutorial(file?: File, wordTutorialId?: number, subtitleLanguageCode?: string, options?: AxiosRequestConfig) {
        return WordTutorialSubtitleAdministrationApiFp(this.configuration).addSubtitleToWordTutorial(file, wordTutorialId, subtitleLanguageCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Kelime eğitiminden bir altyazı dosyasının silinmesini sağlar.
     * @param {number} [subtitleId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialSubtitleAdministrationApi
     */
    public removeSubtitleFromWordTutorial(subtitleId?: number, options?: AxiosRequestConfig) {
        return WordTutorialSubtitleAdministrationApiFp(this.configuration).removeSubtitleFromWordTutorial(subtitleId, options).then((request) => request(this.axios, this.basePath));
    }
}

