/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsAuthenticationAppUserRoleModel } from './advancer-models-authentication-app-user-role-model';

/**
 * 
 * @export
 * @interface AdvancerModelsAuthenticationAppRoleModel
 */
export interface AdvancerModelsAuthenticationAppRoleModel {
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsAuthenticationAppRoleModel
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppRoleModel
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppRoleModel
     */
    'normalizedName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppRoleModel
     */
    'concurrencyStamp'?: string | null;
    /**
     * 
     * @type {Array<AdvancerModelsAuthenticationAppUserRoleModel>}
     * @memberof AdvancerModelsAuthenticationAppRoleModel
     */
    'userRoles'?: Array<AdvancerModelsAuthenticationAppUserRoleModel> | null;
}

