/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
 */
export interface AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel {
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
     */
    'updatedAt': string;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
     */
    'minutesPerDayOption'?: number;
}

