/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsAuthenticationAppRoleModel } from './advancer-models-authentication-app-role-model';
// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsAuthenticationAppUserModel } from './advancer-models-authentication-app-user-model';

/**
 * 
 * @export
 * @interface AdvancerModelsAuthenticationAppUserRoleModel
 */
export interface AdvancerModelsAuthenticationAppUserRoleModel {
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsAuthenticationAppUserRoleModel
     */
    'userId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsAuthenticationAppUserRoleModel
     */
    'roleId'?: number;
    /**
     * 
     * @type {AdvancerModelsAuthenticationAppUserModel}
     * @memberof AdvancerModelsAuthenticationAppUserRoleModel
     */
    'user'?: AdvancerModelsAuthenticationAppUserModel;
    /**
     * 
     * @type {AdvancerModelsAuthenticationAppRoleModel}
     * @memberof AdvancerModelsAuthenticationAppUserRoleModel
     */
    'role'?: AdvancerModelsAuthenticationAppRoleModel;
}

