/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsAuthenticationAppUserRoleModel } from './advancer-models-authentication-app-user-role-model';
// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsRoleMetadataStudentMetadataModel } from './advancer-models-role-metadata-student-metadata-model';
// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsRoleMetadataTeacherMetadataModel } from './advancer-models-role-metadata-teacher-metadata-model';

/**
 * 
 * @export
 * @interface AdvancerModelsAuthenticationAppUserModel
 */
export interface AdvancerModelsAuthenticationAppUserModel {
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'userName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'normalizedUserName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'normalizedEmail'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'emailConfirmed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'passwordHash'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'securityStamp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'concurrencyStamp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'phoneNumberConfirmed'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'twoFactorEnabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'lockoutEnd'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'lockoutEnabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'accessFailedCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'avatarPhotoId'?: string | null;
    /**
     * Güvenlik gerektiren yerlerde(örneğin chat) direk integer id üzerinden işlem yapılmaması gerekebilir.
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'guid'?: string;
    /**
     * Kullanıcının ismi
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'lostPasswordToken'?: string | null;
    /**
     * 
     * @type {Array<AdvancerModelsAuthenticationAppUserRoleModel>}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'userRoles'?: Array<AdvancerModelsAuthenticationAppUserRoleModel> | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'teacherMetadataId'?: number | null;
    /**
     * 
     * @type {AdvancerModelsRoleMetadataTeacherMetadataModel}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'teacherMetadata'?: AdvancerModelsRoleMetadataTeacherMetadataModel;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'studentMetadataId'?: number | null;
    /**
     * 
     * @type {AdvancerModelsRoleMetadataStudentMetadataModel}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'studentMetadata'?: AdvancerModelsRoleMetadataStudentMetadataModel;
    /**
     * 
     * @type {boolean}
     * @memberof AdvancerModelsAuthenticationAppUserModel
     */
    'isAccountDeletedDueGDPR'?: boolean | null;
}

