/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsJoinTableTeacherMetadataTeachingStyleModel } from './advancer-models-join-table-teacher-metadata-teaching-style-model';

/**
 * 
 * @export
 * @interface AdvancerModelsSpecialityTeachingStyleModel
 */
export interface AdvancerModelsSpecialityTeachingStyleModel {
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    'updatedAt': string;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    'enumName'?: string | null;
    /**
     * 
     * @type {Array<AdvancerModelsJoinTableTeacherMetadataTeachingStyleModel>}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    'teachers'?: Array<AdvancerModelsJoinTableTeacherMetadataTeachingStyleModel> | null;
}

