/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsAppointmentAppointmentModel } from './advancer-models-appointment-appointment-model';
// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsLiveRecorderState } from './advancer-models-live-recorder-state';

/**
 * 
 * @export
 * @interface AdvancerModelsLiveAgoraChannelModel
 */
export interface AdvancerModelsLiveAgoraChannelModel {
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'updatedAt': string;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'liveStreamStartsAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'liveStreamEndsAt'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'isLive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'appointmentId'?: number;
    /**
     * 
     * @type {AdvancerModelsAppointmentAppointmentModel}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'appointment'?: AdvancerModelsAppointmentAppointmentModel;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'channelName'?: string;
    /**
     * 
     * @type {AdvancerModelsLiveRecorderState}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'recorderState'?: AdvancerModelsLiveRecorderState;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'recorderResourceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'recorderUid'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'recorderSid'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'whiteBoardRoom'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'roomToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'rtmRoomToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'rtmRoomTokenTeacher'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'startUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'joinUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsLiveAgoraChannelModel
     */
    'zoomMeetResponse'?: string | null;
}



