/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsSubscriptionSubscriptionDayOptionModel } from './advancer-models-subscription-subscription-day-option-model';
// May contain unused imports in some cases
// @ts-ignore
import { AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel } from './advancer-models-subscription-subscription-minutes-per-day-option-model';

/**
 * 
 * @export
 * @interface AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
 */
export interface AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel {
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'updatedAt': string;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'id'?: number;
    /**
     * Süreye verilen başlıktır. Örneğin: \"1 Aylık, 1 Yıl\"  ( DİKKAT: Buraya girilecek değerin client üzerinde dil çevirisi karşılığı olmalıdır. Yoksa ingilizce dilinde çeviriler yanlış gösterilir. )
     * @type {string}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'name'?: string | null;
    /**
     * Paketin süresini tutar.
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'durationAsMonths'?: number;
    /**
     * Toplam paket tutarı üzerine pakete uygulanacak yüzdelik indirimi tutar.
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'discountRate'?: number;
    /**
     * Süreye ait ek bilgilendirme istenirse bu alana girilebilir. Örneğin: \"Bu paketi alırsanız %40 indirim!\"  ( DİKKAT: Buraya girilecek değerin client üzerinde dil çevirisi karşılığı olmalıdır. Yoksa ingilizce dilinde çeviriler yanlış gösterilir. )
     * @type {string}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'totalMinutes'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'dayOptionId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'minuteOptionId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'pricePerMint'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'discountedAmount'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'total'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'totalDiscounted'?: number | null;
    /**
     * 
     * @type {AdvancerModelsSubscriptionSubscriptionDayOptionModel}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'subscriptionDayOptions'?: AdvancerModelsSubscriptionSubscriptionDayOptionModel;
    /**
     * 
     * @type {AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    'subscriptionMinutesPerDayOptions'?: AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel;
}

