/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppointmentAdministrationQueriesTeacherInAppointment
 */
export interface AppointmentAdministrationQueriesTeacherInAppointment {
    /**
     * 
     * @type {number}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'teacherId': number;
    /**
     * 
     * @type {string}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'teacherGuid': string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'avatar1X': string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'avatar2X': string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'avatar3X': string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'avatar4X': string;
    /**
     * Girilebilecek değerler:  NATIVE_US,  NATIVE_BRITISH,  TURKISH,  OTHER
     * @type {string}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'accentType': string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'isOnline': boolean;
    /**
     * 
     * @type {number}
     * @memberof AppointmentAdministrationQueriesTeacherInAppointment
     */
    'rate': number;
}

