/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LegalDocumentQueriesLegalDocumentsListItem
 */
export interface LegalDocumentQueriesLegalDocumentsListItem {
    /**
     * 
     * @type {number}
     * @memberof LegalDocumentQueriesLegalDocumentsListItem
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof LegalDocumentQueriesLegalDocumentsListItem
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof LegalDocumentQueriesLegalDocumentsListItem
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof LegalDocumentQueriesLegalDocumentsListItem
     */
    'content': string;
}

