/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LiveQueriesTeacherDetailsForCall
 */
export interface LiveQueriesTeacherDetailsForCall {
    /**
     * 
     * @type {number}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    'userId'?: number;
    /**
     * 
     * @type {number}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    'metadataId'?: number;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    'avatar1X'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    'avatar2X'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    'avatar3X'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    'avatar4X'?: string | null;
}

