/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentQueriesPaymentInterval
 */
export interface PaymentQueriesPaymentInterval {
    /**
     * Belirlenen sürenin değeridir. Ay cinsindendir.
     * @type {number}
     * @memberof PaymentQueriesPaymentInterval
     */
    'durationValue': number;
    /**
     * İndirim oranı
     * @type {number}
     * @memberof PaymentQueriesPaymentInterval
     */
    'discount'?: number | null;
    /**
     * Örneğin: 1 aylık paket 20% indirimli!
     * @type {string}
     * @memberof PaymentQueriesPaymentInterval
     */
    'shortDescription'?: string | null;
}

