/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReferralQueriesListReferralStudentPagination
 */
export interface ReferralQueriesListReferralStudentPagination {
    /**
     * 
     * @type {number}
     * @memberof ReferralQueriesListReferralStudentPagination
     */
    'totalPages': number;
    /**
     * 
     * @type {number}
     * @memberof ReferralQueriesListReferralStudentPagination
     */
    'recordsPerPage': number;
    /**
     * 
     * @type {number}
     * @memberof ReferralQueriesListReferralStudentPagination
     */
    'currentPage': number;
    /**
     * 
     * @type {number}
     * @memberof ReferralQueriesListReferralStudentPagination
     */
    'totalRecords': number;
}

