/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SchedulerCommandsSchedulerTimeRange
 */
export interface SchedulerCommandsSchedulerTimeRange {
    /**
     * 
     * @type {string}
     * @memberof SchedulerCommandsSchedulerTimeRange
     */
    'startTime': string;
    /**
     * 
     * @type {string}
     * @memberof SchedulerCommandsSchedulerTimeRange
     */
    'endTime': string;
    /**
     * 
     * @type {boolean}
     * @memberof SchedulerCommandsSchedulerTimeRange
     */
    'isAdded': boolean;
}

