/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TeacherAdministrationQueriesTeacherSalariesListItem
 */
export interface TeacherAdministrationQueriesTeacherSalariesListItem {
    /**
     * 
     * @type {number}
     * @memberof TeacherAdministrationQueriesTeacherSalariesListItem
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TeacherAdministrationQueriesTeacherSalariesListItem
     */
    'name'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeacherAdministrationQueriesTeacherSalariesListItem
     */
    'minutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof TeacherAdministrationQueriesTeacherSalariesListItem
     */
    'earnedAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TeacherAdministrationQueriesTeacherSalariesListItem
     */
    'hourlyRate'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeacherAdministrationQueriesTeacherSalariesListItem
     */
    'hours'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherAdministrationQueriesTeacherSalariesListItem
     */
    'paymentStatus'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherAdministrationQueriesTeacherSalariesListItem
     */
    'startDate'?: string;
}

