/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VideoRecordQueriesStudentInformationForVideoRecord
 */
export interface VideoRecordQueriesStudentInformationForVideoRecord {
    /**
     * 
     * @type {number}
     * @memberof VideoRecordQueriesStudentInformationForVideoRecord
     */
    'studentId': number;
    /**
     * 
     * @type {string}
     * @memberof VideoRecordQueriesStudentInformationForVideoRecord
     */
    'avatar1X': string;
    /**
     * 
     * @type {string}
     * @memberof VideoRecordQueriesStudentInformationForVideoRecord
     */
    'avatar2X': string;
    /**
     * 
     * @type {string}
     * @memberof VideoRecordQueriesStudentInformationForVideoRecord
     */
    'avatar3X': string;
    /**
     * 
     * @type {string}
     * @memberof VideoRecordQueriesStudentInformationForVideoRecord
     */
    'avatar4X': string;
    /**
     * 
     * @type {string}
     * @memberof VideoRecordQueriesStudentInformationForVideoRecord
     */
    'name': string;
}

