/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WordTutorialQueriesWordTutorialSubtitle } from './word-tutorial-queries-word-tutorial-subtitle';
// May contain unused imports in some cases
// @ts-ignore
import { WordTutorialQueriesWordTutorialTranslation } from './word-tutorial-queries-word-tutorial-translation';

/**
 * 
 * @export
 * @interface WordTutorialQueriesFavoriteWordTutorial
 */
export interface WordTutorialQueriesFavoriteWordTutorial {
    /**
     * 
     * @type {number}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'wordTutorialId': number;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'slug': string;
    /**
     * 
     * @type {boolean}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'isFavorited': boolean;
    /**
     * 
     * @type {number}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'wordTutorialCategoryId': number;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'wordTutorialCategorySlug': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'coverImage1X': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'coverImage2X': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'coverImage3X': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'coverImage4X': string;
    /**
     * 
     * @type {Array<WordTutorialQueriesWordTutorialTranslation>}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'translations': Array<WordTutorialQueriesWordTutorialTranslation>;
    /**
     * 
     * @type {Array<WordTutorialQueriesWordTutorialSubtitle>}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    'subtitles': Array<WordTutorialQueriesWordTutorialSubtitle>;
}

