/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WordTutorialCategoryQueriesWordTutorial } from './word-tutorial-category-queries-word-tutorial';

/**
 * 
 * @export
 * @interface WordTutorialCategoryQueriesWordTutorialCategoryInList
 */
export interface WordTutorialCategoryQueriesWordTutorialCategoryInList {
    /**
     * 
     * @type {number}
     * @memberof WordTutorialCategoryQueriesWordTutorialCategoryInList
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialCategoryQueriesWordTutorialCategoryInList
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialCategoryQueriesWordTutorialCategoryInList
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialCategoryQueriesWordTutorialCategoryInList
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialCategoryQueriesWordTutorialCategoryInList
     */
    'coverImage1X': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialCategoryQueriesWordTutorialCategoryInList
     */
    'coverImage2X': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialCategoryQueriesWordTutorialCategoryInList
     */
    'coverImage3X': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialCategoryQueriesWordTutorialCategoryInList
     */
    'coverImage4X': string;
    /**
     * 
     * @type {Array<WordTutorialCategoryQueriesWordTutorial>}
     * @memberof WordTutorialCategoryQueriesWordTutorialCategoryInList
     */
    'wordTutorials': Array<WordTutorialCategoryQueriesWordTutorial>;
}

