/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WordTutorialCategoryQueriesSubtitleContent } from './word-tutorial-category-queries-subtitle-content';

/**
 * 
 * @export
 * @interface WordTutorialCategoryQueriesWordTutorialSubtitle
 */
export interface WordTutorialCategoryQueriesWordTutorialSubtitle {
    /**
     * 
     * @type {string}
     * @memberof WordTutorialCategoryQueriesWordTutorialSubtitle
     */
    'languageCode': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialCategoryQueriesWordTutorialSubtitle
     */
    'subtitlePath': string;
    /**
     * 
     * @type {Array<WordTutorialCategoryQueriesSubtitleContent>}
     * @memberof WordTutorialCategoryQueriesWordTutorialSubtitle
     */
    'lines': Array<WordTutorialCategoryQueriesSubtitleContent>;
}

