/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WordTutorialAdministrationQueriesSubtitleLine } from './word-tutorial-administration-queries-subtitle-line';

/**
 * 
 * @export
 * @interface WordTutorialAdministrationQueriesWordTutorialSubtitleListItem
 */
export interface WordTutorialAdministrationQueriesWordTutorialSubtitleListItem {
    /**
     * Kelime eğitimi, altyazı dosyasının linkini barındırır
     * @type {string}
     * @memberof WordTutorialAdministrationQueriesWordTutorialSubtitleListItem
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialAdministrationQueriesWordTutorialSubtitleListItem
     */
    'languageCode': string;
    /**
     * 
     * @type {Array<WordTutorialAdministrationQueriesSubtitleLine>}
     * @memberof WordTutorialAdministrationQueriesWordTutorialSubtitleListItem
     */
    'lines': Array<WordTutorialAdministrationQueriesSubtitleLine>;
}

