/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FluentValidationResultsValidationFailure,
  WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult,
} from '../models/index';
import {
    FluentValidationResultsValidationFailureFromJSON,
    FluentValidationResultsValidationFailureToJSON,
    WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResultFromJSON,
    WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResultToJSON,
} from '../models/index';

export interface AddSubtitleToWordTutorialRequest {
    wordTutorialId?: number;
    subtitleLanguageCode?: string;
    file?: Blob;
}

export interface RemoveSubtitleFromWordTutorialRequest {
    subtitleId?: number;
}

/**
 * 
 */
export class WordTutorialSubtitleAdministrationApi extends runtime.BaseAPI {

    /**
     * Kelime eğitimine ait yeni bir çeviri dosyası yüklenmesini sağlar.
     */
    async addSubtitleToWordTutorialRaw(requestParameters: AddSubtitleToWordTutorialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult>> {
        const queryParameters: any = {};

        if (requestParameters.wordTutorialId !== undefined) {
            queryParameters['WordTutorialId'] = requestParameters.wordTutorialId;
        }

        if (requestParameters.subtitleLanguageCode !== undefined) {
            queryParameters['SubtitleLanguageCode'] = requestParameters.subtitleLanguageCode;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.file !== undefined) {
            formParams.append('File', requestParameters.file as any);
        }

        const response = await this.request({
            path: `/api/WordTutorialSubtitleAdministration/AddSubtitleToWordTutorial`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResultFromJSON(jsonValue));
    }

    /**
     * Kelime eğitimine ait yeni bir çeviri dosyası yüklenmesini sağlar.
     */
    async addSubtitleToWordTutorial(requestParameters: AddSubtitleToWordTutorialRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult> {
        const response = await this.addSubtitleToWordTutorialRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Kelime eğitiminden bir altyazı dosyasının silinmesini sağlar.
     */
    async removeSubtitleFromWordTutorialRaw(requestParameters: RemoveSubtitleFromWordTutorialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters.subtitleId !== undefined) {
            queryParameters['SubtitleId'] = requestParameters.subtitleId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/WordTutorialSubtitleAdministration/RemoveSubtitleFromWordTutorial`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Kelime eğitiminden bir altyazı dosyasının silinmesini sağlar.
     */
    async removeSubtitleFromWordTutorial(requestParameters: RemoveSubtitleFromWordTutorialRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.removeSubtitleFromWordTutorialRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
