/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdministratorCommandsLoginCommandResult
 */
export interface AdministratorCommandsLoginCommandResult {
    /**
     * Oluşturulan jwt.
     * @type {string}
     * @memberof AdministratorCommandsLoginCommandResult
     */
    jwt: string;
}

/**
 * Check if a given object implements the AdministratorCommandsLoginCommandResult interface.
 */
export function instanceOfAdministratorCommandsLoginCommandResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "jwt" in value;

    return isInstance;
}

export function AdministratorCommandsLoginCommandResultFromJSON(json: any): AdministratorCommandsLoginCommandResult {
    return AdministratorCommandsLoginCommandResultFromJSONTyped(json, false);
}

export function AdministratorCommandsLoginCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdministratorCommandsLoginCommandResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jwt': json['jwt'],
    };
}

export function AdministratorCommandsLoginCommandResultToJSON(value?: AdministratorCommandsLoginCommandResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jwt': value.jwt,
    };
}

