/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AdvancerModelsRoleMetadataTeacherMetadataModel } from './AdvancerModelsRoleMetadataTeacherMetadataModel';
import {
    AdvancerModelsRoleMetadataTeacherMetadataModelFromJSON,
    AdvancerModelsRoleMetadataTeacherMetadataModelFromJSONTyped,
    AdvancerModelsRoleMetadataTeacherMetadataModelToJSON,
} from './AdvancerModelsRoleMetadataTeacherMetadataModel';
import type { AdvancerModelsSpecialityLanguageLevelModel } from './AdvancerModelsSpecialityLanguageLevelModel';
import {
    AdvancerModelsSpecialityLanguageLevelModelFromJSON,
    AdvancerModelsSpecialityLanguageLevelModelFromJSONTyped,
    AdvancerModelsSpecialityLanguageLevelModelToJSON,
} from './AdvancerModelsSpecialityLanguageLevelModel';

/**
 * 
 * @export
 * @interface AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel
 */
export interface AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel {
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel
     */
    teacherMetadataId?: number;
    /**
     * 
     * @type {AdvancerModelsRoleMetadataTeacherMetadataModel}
     * @memberof AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel
     */
    teacherMetadata?: AdvancerModelsRoleMetadataTeacherMetadataModel;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel
     */
    languageLevelId?: number;
    /**
     * 
     * @type {AdvancerModelsSpecialityLanguageLevelModel}
     * @memberof AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel
     */
    languageLevel?: AdvancerModelsSpecialityLanguageLevelModel;
}

/**
 * Check if a given object implements the AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel interface.
 */
export function instanceOfAdvancerModelsJoinTableTeacherMetadataLanguageLevelModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AdvancerModelsJoinTableTeacherMetadataLanguageLevelModelFromJSON(json: any): AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel {
    return AdvancerModelsJoinTableTeacherMetadataLanguageLevelModelFromJSONTyped(json, false);
}

export function AdvancerModelsJoinTableTeacherMetadataLanguageLevelModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teacherMetadataId': !exists(json, 'teacherMetadataId') ? undefined : json['teacherMetadataId'],
        'teacherMetadata': !exists(json, 'teacherMetadata') ? undefined : AdvancerModelsRoleMetadataTeacherMetadataModelFromJSON(json['teacherMetadata']),
        'languageLevelId': !exists(json, 'languageLevelId') ? undefined : json['languageLevelId'],
        'languageLevel': !exists(json, 'languageLevel') ? undefined : AdvancerModelsSpecialityLanguageLevelModelFromJSON(json['languageLevel']),
    };
}

export function AdvancerModelsJoinTableTeacherMetadataLanguageLevelModelToJSON(value?: AdvancerModelsJoinTableTeacherMetadataLanguageLevelModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teacherMetadataId': value.teacherMetadataId,
        'teacherMetadata': AdvancerModelsRoleMetadataTeacherMetadataModelToJSON(value.teacherMetadata),
        'languageLevelId': value.languageLevelId,
        'languageLevel': AdvancerModelsSpecialityLanguageLevelModelToJSON(value.languageLevel),
    };
}

