/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
 */
export interface AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel {
    /**
     * 
     * @type {Date}
     * @memberof AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel
     */
    minutesPerDayOption?: number;
}

/**
 * Check if a given object implements the AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel interface.
 */
export function instanceOfAdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelFromJSON(json: any): AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel {
    return AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelFromJSONTyped(json, false);
}

export function AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'minutesPerDayOption': !exists(json, 'minutesPerDayOption') ? undefined : json['minutesPerDayOption'],
    };
}

export function AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelToJSON(value?: AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'id': value.id,
        'minutesPerDayOption': value.minutesPerDayOption,
    };
}

