/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AdvancerModelsSubscriptionSubscriptionDayOptionModel } from './AdvancerModelsSubscriptionSubscriptionDayOptionModel';
import {
    AdvancerModelsSubscriptionSubscriptionDayOptionModelFromJSON,
    AdvancerModelsSubscriptionSubscriptionDayOptionModelFromJSONTyped,
    AdvancerModelsSubscriptionSubscriptionDayOptionModelToJSON,
} from './AdvancerModelsSubscriptionSubscriptionDayOptionModel';
import type { AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel } from './AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel';
import {
    AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelFromJSON,
    AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelFromJSONTyped,
    AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelToJSON,
} from './AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel';

/**
 * 
 * @export
 * @interface AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
 */
export interface AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel {
    /**
     * 
     * @type {Date}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    id?: number;
    /**
     * Süreye verilen başlıktır. Örneğin: "1 Aylık, 1 Yıl"
     * ( DİKKAT: Buraya girilecek değerin client üzerinde dil çevirisi karşılığı olmalıdır. Yoksa ingilizce dilinde çeviriler yanlış gösterilir. )
     * @type {string}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    name?: string | null;
    /**
     * Paketin süresini tutar.
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    durationAsMonths?: number;
    /**
     * Toplam paket tutarı üzerine pakete uygulanacak yüzdelik indirimi tutar.
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    discountRate?: number;
    /**
     * Süreye ait ek bilgilendirme istenirse bu alana girilebilir. Örneğin: "Bu paketi alırsanız %40 indirim!"
     * ( DİKKAT: Buraya girilecek değerin client üzerinde dil çevirisi karşılığı olmalıdır. Yoksa ingilizce dilinde çeviriler yanlış gösterilir. )
     * @type {string}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    totalMinutes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    dayOptionId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    minuteOptionId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    pricePerMint?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    discountedAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    total?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    totalDiscounted?: number | null;
    /**
     * 
     * @type {AdvancerModelsSubscriptionSubscriptionDayOptionModel}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    subscriptionDayOptions?: AdvancerModelsSubscriptionSubscriptionDayOptionModel;
    /**
     * 
     * @type {AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel}
     * @memberof AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel
     */
    subscriptionMinutesPerDayOptions?: AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel;
}

/**
 * Check if a given object implements the AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel interface.
 */
export function instanceOfAdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModelFromJSON(json: any): AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel {
    return AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModelFromJSONTyped(json, false);
}

export function AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'durationAsMonths': !exists(json, 'durationAsMonths') ? undefined : json['durationAsMonths'],
        'discountRate': !exists(json, 'discountRate') ? undefined : json['discountRate'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'totalMinutes': !exists(json, 'totalMinutes') ? undefined : json['totalMinutes'],
        'dayOptionId': !exists(json, 'dayOptionId') ? undefined : json['dayOptionId'],
        'minuteOptionId': !exists(json, 'minuteOptionId') ? undefined : json['minuteOptionId'],
        'pricePerMint': !exists(json, 'pricePerMint') ? undefined : json['pricePerMint'],
        'discountedAmount': !exists(json, 'discountedAmount') ? undefined : json['discountedAmount'],
        'total': !exists(json, 'total') ? undefined : json['total'],
        'totalDiscounted': !exists(json, 'totalDiscounted') ? undefined : json['totalDiscounted'],
        'subscriptionDayOptions': !exists(json, 'subscriptionDayOptions') ? undefined : AdvancerModelsSubscriptionSubscriptionDayOptionModelFromJSON(json['subscriptionDayOptions']),
        'subscriptionMinutesPerDayOptions': !exists(json, 'subscriptionMinutesPerDayOptions') ? undefined : AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelFromJSON(json['subscriptionMinutesPerDayOptions']),
    };
}

export function AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModelToJSON(value?: AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'id': value.id,
        'name': value.name,
        'durationAsMonths': value.durationAsMonths,
        'discountRate': value.discountRate,
        'description': value.description,
        'totalMinutes': value.totalMinutes,
        'dayOptionId': value.dayOptionId,
        'minuteOptionId': value.minuteOptionId,
        'pricePerMint': value.pricePerMint,
        'discountedAmount': value.discountedAmount,
        'total': value.total,
        'totalDiscounted': value.totalDiscounted,
        'subscriptionDayOptions': AdvancerModelsSubscriptionSubscriptionDayOptionModelToJSON(value.subscriptionDayOptions),
        'subscriptionMinutesPerDayOptions': AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelToJSON(value.subscriptionMinutesPerDayOptions),
    };
}

