/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdvancerModelsSubscriptionSubscriptionDayOptionModel
 */
export interface AdvancerModelsSubscriptionSubscriptionDayOptionModel {
    /**
     * 
     * @type {Date}
     * @memberof AdvancerModelsSubscriptionSubscriptionDayOptionModel
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdvancerModelsSubscriptionSubscriptionDayOptionModel
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionDayOptionModel
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSubscriptionSubscriptionDayOptionModel
     */
    dayOption?: number;
}

/**
 * Check if a given object implements the AdvancerModelsSubscriptionSubscriptionDayOptionModel interface.
 */
export function instanceOfAdvancerModelsSubscriptionSubscriptionDayOptionModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function AdvancerModelsSubscriptionSubscriptionDayOptionModelFromJSON(json: any): AdvancerModelsSubscriptionSubscriptionDayOptionModel {
    return AdvancerModelsSubscriptionSubscriptionDayOptionModelFromJSONTyped(json, false);
}

export function AdvancerModelsSubscriptionSubscriptionDayOptionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvancerModelsSubscriptionSubscriptionDayOptionModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'dayOption': !exists(json, 'dayOption') ? undefined : json['dayOption'],
    };
}

export function AdvancerModelsSubscriptionSubscriptionDayOptionModelToJSON(value?: AdvancerModelsSubscriptionSubscriptionDayOptionModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'id': value.id,
        'dayOption': value.dayOption,
    };
}

