/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AdvancerModelsJoinTableTeacherMetadataTeachingStyleModel } from './AdvancerModelsJoinTableTeacherMetadataTeachingStyleModel';
import {
    AdvancerModelsJoinTableTeacherMetadataTeachingStyleModelFromJSON,
    AdvancerModelsJoinTableTeacherMetadataTeachingStyleModelFromJSONTyped,
    AdvancerModelsJoinTableTeacherMetadataTeachingStyleModelToJSON,
} from './AdvancerModelsJoinTableTeacherMetadataTeachingStyleModel';

/**
 * 
 * @export
 * @interface AdvancerModelsSpecialityTeachingStyleModel
 */
export interface AdvancerModelsSpecialityTeachingStyleModel {
    /**
     * 
     * @type {Date}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    enumName?: string | null;
    /**
     * 
     * @type {Array<AdvancerModelsJoinTableTeacherMetadataTeachingStyleModel>}
     * @memberof AdvancerModelsSpecialityTeachingStyleModel
     */
    teachers?: Array<AdvancerModelsJoinTableTeacherMetadataTeachingStyleModel> | null;
}

/**
 * Check if a given object implements the AdvancerModelsSpecialityTeachingStyleModel interface.
 */
export function instanceOfAdvancerModelsSpecialityTeachingStyleModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function AdvancerModelsSpecialityTeachingStyleModelFromJSON(json: any): AdvancerModelsSpecialityTeachingStyleModel {
    return AdvancerModelsSpecialityTeachingStyleModelFromJSONTyped(json, false);
}

export function AdvancerModelsSpecialityTeachingStyleModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvancerModelsSpecialityTeachingStyleModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'enumName': !exists(json, 'enumName') ? undefined : json['enumName'],
        'teachers': !exists(json, 'teachers') ? undefined : (json['teachers'] === null ? null : (json['teachers'] as Array<any>).map(AdvancerModelsJoinTableTeacherMetadataTeachingStyleModelFromJSON)),
    };
}

export function AdvancerModelsSpecialityTeachingStyleModelToJSON(value?: AdvancerModelsSpecialityTeachingStyleModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'id': value.id,
        'enumName': value.enumName,
        'teachers': value.teachers === undefined ? undefined : (value.teachers === null ? null : (value.teachers as Array<any>).map(AdvancerModelsJoinTableTeacherMetadataTeachingStyleModelToJSON)),
    };
}

