/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppointmentCommandsCreateCommandResult
 */
export interface AppointmentCommandsCreateCommandResult {
    /**
     * 
     * @type {number}
     * @memberof AppointmentCommandsCreateCommandResult
     */
    appointmentId: number;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentCommandsCreateCommandResult
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentCommandsCreateCommandResult
     */
    endTime: Date;
}

/**
 * Check if a given object implements the AppointmentCommandsCreateCommandResult interface.
 */
export function instanceOfAppointmentCommandsCreateCommandResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "appointmentId" in value;
    isInstance = isInstance && "startTime" in value;
    isInstance = isInstance && "endTime" in value;

    return isInstance;
}

export function AppointmentCommandsCreateCommandResultFromJSON(json: any): AppointmentCommandsCreateCommandResult {
    return AppointmentCommandsCreateCommandResultFromJSONTyped(json, false);
}

export function AppointmentCommandsCreateCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentCommandsCreateCommandResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appointmentId': json['appointmentId'],
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
    };
}

export function AppointmentCommandsCreateCommandResultToJSON(value?: AppointmentCommandsCreateCommandResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appointmentId': value.appointmentId,
        'startTime': (value.startTime.toISOString()),
        'endTime': (value.endTime.toISOString()),
    };
}

