/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppointmentAdministrationQueriesStudentInAppointment } from './AppointmentAdministrationQueriesStudentInAppointment';
import {
    AppointmentAdministrationQueriesStudentInAppointmentFromJSON,
    AppointmentAdministrationQueriesStudentInAppointmentFromJSONTyped,
    AppointmentAdministrationQueriesStudentInAppointmentToJSON,
} from './AppointmentAdministrationQueriesStudentInAppointment';
import type { AppointmentAdministrationQueriesTeacherInAppointment } from './AppointmentAdministrationQueriesTeacherInAppointment';
import {
    AppointmentAdministrationQueriesTeacherInAppointmentFromJSON,
    AppointmentAdministrationQueriesTeacherInAppointmentFromJSONTyped,
    AppointmentAdministrationQueriesTeacherInAppointmentToJSON,
} from './AppointmentAdministrationQueriesTeacherInAppointment';

/**
 * 
 * @export
 * @interface AppointmentAdministrationQueriesAppointmentListItem
 */
export interface AppointmentAdministrationQueriesAppointmentListItem {
    /**
     * 
     * @type {number}
     * @memberof AppointmentAdministrationQueriesAppointmentListItem
     */
    appointmentId: number;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentAdministrationQueriesAppointmentListItem
     */
    startDateTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentAdministrationQueriesAppointmentListItem
     */
    endDateTime: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentAdministrationQueriesAppointmentListItem
     */
    isVideoCallRoomOpened: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentAdministrationQueriesAppointmentListItem
     */
    isRatingCompleted: boolean;
    /**
     * 
     * @type {number}
     * @memberof AppointmentAdministrationQueriesAppointmentListItem
     */
    rating?: number | null;
    /**
     * Kullanıcının bu randevunun vaktini değiştirme hakkı var ise true döner.
     * @type {boolean}
     * @memberof AppointmentAdministrationQueriesAppointmentListItem
     */
    isAppointmentDateTimeChangeable: boolean;
    /**
     * 
     * @type {AppointmentAdministrationQueriesTeacherInAppointment}
     * @memberof AppointmentAdministrationQueriesAppointmentListItem
     */
    teacher: AppointmentAdministrationQueriesTeacherInAppointment;
    /**
     * 
     * @type {AppointmentAdministrationQueriesStudentInAppointment}
     * @memberof AppointmentAdministrationQueriesAppointmentListItem
     */
    student: AppointmentAdministrationQueriesStudentInAppointment;
}

/**
 * Check if a given object implements the AppointmentAdministrationQueriesAppointmentListItem interface.
 */
export function instanceOfAppointmentAdministrationQueriesAppointmentListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "appointmentId" in value;
    isInstance = isInstance && "startDateTime" in value;
    isInstance = isInstance && "endDateTime" in value;
    isInstance = isInstance && "isVideoCallRoomOpened" in value;
    isInstance = isInstance && "isRatingCompleted" in value;
    isInstance = isInstance && "isAppointmentDateTimeChangeable" in value;
    isInstance = isInstance && "teacher" in value;
    isInstance = isInstance && "student" in value;

    return isInstance;
}

export function AppointmentAdministrationQueriesAppointmentListItemFromJSON(json: any): AppointmentAdministrationQueriesAppointmentListItem {
    return AppointmentAdministrationQueriesAppointmentListItemFromJSONTyped(json, false);
}

export function AppointmentAdministrationQueriesAppointmentListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentAdministrationQueriesAppointmentListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appointmentId': json['appointmentId'],
        'startDateTime': (new Date(json['startDateTime'])),
        'endDateTime': (new Date(json['endDateTime'])),
        'isVideoCallRoomOpened': json['isVideoCallRoomOpened'],
        'isRatingCompleted': json['isRatingCompleted'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'isAppointmentDateTimeChangeable': json['isAppointmentDateTimeChangeable'],
        'teacher': AppointmentAdministrationQueriesTeacherInAppointmentFromJSON(json['teacher']),
        'student': AppointmentAdministrationQueriesStudentInAppointmentFromJSON(json['student']),
    };
}

export function AppointmentAdministrationQueriesAppointmentListItemToJSON(value?: AppointmentAdministrationQueriesAppointmentListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appointmentId': value.appointmentId,
        'startDateTime': (value.startDateTime.toISOString()),
        'endDateTime': (value.endDateTime.toISOString()),
        'isVideoCallRoomOpened': value.isVideoCallRoomOpened,
        'isRatingCompleted': value.isRatingCompleted,
        'rating': value.rating,
        'isAppointmentDateTimeChangeable': value.isAppointmentDateTimeChangeable,
        'teacher': AppointmentAdministrationQueriesTeacherInAppointmentToJSON(value.teacher),
        'student': AppointmentAdministrationQueriesStudentInAppointmentToJSON(value.student),
    };
}

