/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppointmentCommandsReportAsStudentCommandResult
 */
export interface AppointmentCommandsReportAsStudentCommandResult {
    /**
     * 
     * @type {string}
     * @memberof AppointmentCommandsReportAsStudentCommandResult
     */
    reportId: string;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentCommandsReportAsStudentCommandResult
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof AppointmentCommandsReportAsStudentCommandResult
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentCommandsReportAsStudentCommandResult
     */
    description?: string | null;
}

/**
 * Check if a given object implements the AppointmentCommandsReportAsStudentCommandResult interface.
 */
export function instanceOfAppointmentCommandsReportAsStudentCommandResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reportId" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function AppointmentCommandsReportAsStudentCommandResultFromJSON(json: any): AppointmentCommandsReportAsStudentCommandResult {
    return AppointmentCommandsReportAsStudentCommandResultFromJSONTyped(json, false);
}

export function AppointmentCommandsReportAsStudentCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentCommandsReportAsStudentCommandResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reportId': json['reportId'],
        'createdAt': (new Date(json['createdAt'])),
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function AppointmentCommandsReportAsStudentCommandResultToJSON(value?: AppointmentCommandsReportAsStudentCommandResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reportId': value.reportId,
        'createdAt': (value.createdAt.toISOString()),
        'title': value.title,
        'description': value.description,
    };
}

