/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCommandsReportChatAsStudentCommandResult
 */
export interface ChatCommandsReportChatAsStudentCommandResult {
    /**
     * 
     * @type {number}
     * @memberof ChatCommandsReportChatAsStudentCommandResult
     */
    reportId: number;
    /**
     * 
     * @type {Date}
     * @memberof ChatCommandsReportChatAsStudentCommandResult
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ChatCommandsReportChatAsStudentCommandResult interface.
 */
export function instanceOfChatCommandsReportChatAsStudentCommandResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reportId" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function ChatCommandsReportChatAsStudentCommandResultFromJSON(json: any): ChatCommandsReportChatAsStudentCommandResult {
    return ChatCommandsReportChatAsStudentCommandResultFromJSONTyped(json, false);
}

export function ChatCommandsReportChatAsStudentCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCommandsReportChatAsStudentCommandResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reportId': json['reportId'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ChatCommandsReportChatAsStudentCommandResultToJSON(value?: ChatCommandsReportChatAsStudentCommandResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reportId': value.reportId,
        'createdAt': (value.createdAt.toISOString()),
    };
}

