/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerServiceCommandsSendContactMessageCommandResult
 */
export interface CustomerServiceCommandsSendContactMessageCommandResult {
    /**
     * 
     * @type {string}
     * @memberof CustomerServiceCommandsSendContactMessageCommandResult
     */
    contactCaseId: string;
}

/**
 * Check if a given object implements the CustomerServiceCommandsSendContactMessageCommandResult interface.
 */
export function instanceOfCustomerServiceCommandsSendContactMessageCommandResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contactCaseId" in value;

    return isInstance;
}

export function CustomerServiceCommandsSendContactMessageCommandResultFromJSON(json: any): CustomerServiceCommandsSendContactMessageCommandResult {
    return CustomerServiceCommandsSendContactMessageCommandResultFromJSONTyped(json, false);
}

export function CustomerServiceCommandsSendContactMessageCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerServiceCommandsSendContactMessageCommandResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contactCaseId': json['contactCaseId'],
    };
}

export function CustomerServiceCommandsSendContactMessageCommandResultToJSON(value?: CustomerServiceCommandsSendContactMessageCommandResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contactCaseId': value.contactCaseId,
    };
}

