/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IyzicoSubscriptionCommandsUpdateCommand
 */
export interface IyzicoSubscriptionCommandsUpdateCommand {
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionCommandsUpdateCommand
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionCommandsUpdateCommand
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionCommandsUpdateCommand
     */
    dayOptionId?: number;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionCommandsUpdateCommand
     */
    minutesPerDayOptionId?: number;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionCommandsUpdateCommand
     */
    packageDurationOptionId?: number;
    /**
     * 
     * @type {string}
     * @memberof IyzicoSubscriptionCommandsUpdateCommand
     */
    iyzicoPlanId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionCommandsUpdateCommand
     */
    referralId?: number | null;
}

/**
 * Check if a given object implements the IyzicoSubscriptionCommandsUpdateCommand interface.
 */
export function instanceOfIyzicoSubscriptionCommandsUpdateCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IyzicoSubscriptionCommandsUpdateCommandFromJSON(json: any): IyzicoSubscriptionCommandsUpdateCommand {
    return IyzicoSubscriptionCommandsUpdateCommandFromJSONTyped(json, false);
}

export function IyzicoSubscriptionCommandsUpdateCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): IyzicoSubscriptionCommandsUpdateCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'dayOptionId': !exists(json, 'dayOptionId') ? undefined : json['dayOptionId'],
        'minutesPerDayOptionId': !exists(json, 'minutesPerDayOptionId') ? undefined : json['minutesPerDayOptionId'],
        'packageDurationOptionId': !exists(json, 'packageDurationOptionId') ? undefined : json['packageDurationOptionId'],
        'iyzicoPlanId': !exists(json, 'iyzicoPlanId') ? undefined : json['iyzicoPlanId'],
        'referralId': !exists(json, 'referralId') ? undefined : json['referralId'],
    };
}

export function IyzicoSubscriptionCommandsUpdateCommandToJSON(value?: IyzicoSubscriptionCommandsUpdateCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'price': value.price,
        'dayOptionId': value.dayOptionId,
        'minutesPerDayOptionId': value.minutesPerDayOptionId,
        'packageDurationOptionId': value.packageDurationOptionId,
        'iyzicoPlanId': value.iyzicoPlanId,
        'referralId': value.referralId,
    };
}

