/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IyzicoSubscriptionQueriesCommonSubscriptionDropdown
 */
export interface IyzicoSubscriptionQueriesCommonSubscriptionDropdown {
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionQueriesCommonSubscriptionDropdown
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IyzicoSubscriptionQueriesCommonSubscriptionDropdown
     */
    value?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IyzicoSubscriptionQueriesCommonSubscriptionDropdown
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionQueriesCommonSubscriptionDropdown
     */
    days?: number;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionQueriesCommonSubscriptionDropdown
     */
    mints?: number;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionQueriesCommonSubscriptionDropdown
     */
    totalDiscounted?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionQueriesCommonSubscriptionDropdown
     */
    dayOptionId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionQueriesCommonSubscriptionDropdown
     */
    minuteOptionId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IyzicoSubscriptionQueriesCommonSubscriptionDropdown
     */
    totalMinutes?: number | null;
}

/**
 * Check if a given object implements the IyzicoSubscriptionQueriesCommonSubscriptionDropdown interface.
 */
export function instanceOfIyzicoSubscriptionQueriesCommonSubscriptionDropdown(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IyzicoSubscriptionQueriesCommonSubscriptionDropdownFromJSON(json: any): IyzicoSubscriptionQueriesCommonSubscriptionDropdown {
    return IyzicoSubscriptionQueriesCommonSubscriptionDropdownFromJSONTyped(json, false);
}

export function IyzicoSubscriptionQueriesCommonSubscriptionDropdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): IyzicoSubscriptionQueriesCommonSubscriptionDropdown {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'days': !exists(json, 'days') ? undefined : json['days'],
        'mints': !exists(json, 'mints') ? undefined : json['mints'],
        'totalDiscounted': !exists(json, 'totalDiscounted') ? undefined : json['totalDiscounted'],
        'dayOptionId': !exists(json, 'dayOptionId') ? undefined : json['dayOptionId'],
        'minuteOptionId': !exists(json, 'minuteOptionId') ? undefined : json['minuteOptionId'],
        'totalMinutes': !exists(json, 'totalMinutes') ? undefined : json['totalMinutes'],
    };
}

export function IyzicoSubscriptionQueriesCommonSubscriptionDropdownToJSON(value?: IyzicoSubscriptionQueriesCommonSubscriptionDropdown | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'value': value.value,
        'description': value.description,
        'days': value.days,
        'mints': value.mints,
        'totalDiscounted': value.totalDiscounted,
        'dayOptionId': value.dayOptionId,
        'minuteOptionId': value.minuteOptionId,
        'totalMinutes': value.totalMinutes,
    };
}

