/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LegalDocumentAdministrationQueriesAdminLegalDocumentList } from './LegalDocumentAdministrationQueriesAdminLegalDocumentList';
import {
    LegalDocumentAdministrationQueriesAdminLegalDocumentListFromJSON,
    LegalDocumentAdministrationQueriesAdminLegalDocumentListFromJSONTyped,
    LegalDocumentAdministrationQueriesAdminLegalDocumentListToJSON,
} from './LegalDocumentAdministrationQueriesAdminLegalDocumentList';

/**
 * 
 * @export
 * @interface LegalDocumentAdministrationQueriesGetAllQueryResult
 */
export interface LegalDocumentAdministrationQueriesGetAllQueryResult {
    /**
     * 
     * @type {Array<LegalDocumentAdministrationQueriesAdminLegalDocumentList>}
     * @memberof LegalDocumentAdministrationQueriesGetAllQueryResult
     */
    legalDocuments: Array<LegalDocumentAdministrationQueriesAdminLegalDocumentList>;
}

/**
 * Check if a given object implements the LegalDocumentAdministrationQueriesGetAllQueryResult interface.
 */
export function instanceOfLegalDocumentAdministrationQueriesGetAllQueryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "legalDocuments" in value;

    return isInstance;
}

export function LegalDocumentAdministrationQueriesGetAllQueryResultFromJSON(json: any): LegalDocumentAdministrationQueriesGetAllQueryResult {
    return LegalDocumentAdministrationQueriesGetAllQueryResultFromJSONTyped(json, false);
}

export function LegalDocumentAdministrationQueriesGetAllQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalDocumentAdministrationQueriesGetAllQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'legalDocuments': ((json['legalDocuments'] as Array<any>).map(LegalDocumentAdministrationQueriesAdminLegalDocumentListFromJSON)),
    };
}

export function LegalDocumentAdministrationQueriesGetAllQueryResultToJSON(value?: LegalDocumentAdministrationQueriesGetAllQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'legalDocuments': ((value.legalDocuments as Array<any>).map(LegalDocumentAdministrationQueriesAdminLegalDocumentListToJSON)),
    };
}

