/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LegalDocumentAdministrationQueriesAdminLegalDocumentList
 */
export interface LegalDocumentAdministrationQueriesAdminLegalDocumentList {
    /**
     * 
     * @type {number}
     * @memberof LegalDocumentAdministrationQueriesAdminLegalDocumentList
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LegalDocumentAdministrationQueriesAdminLegalDocumentList
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof LegalDocumentAdministrationQueriesAdminLegalDocumentList
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof LegalDocumentAdministrationQueriesAdminLegalDocumentList
     */
    content: string;
}

/**
 * Check if a given object implements the LegalDocumentAdministrationQueriesAdminLegalDocumentList interface.
 */
export function instanceOfLegalDocumentAdministrationQueriesAdminLegalDocumentList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function LegalDocumentAdministrationQueriesAdminLegalDocumentListFromJSON(json: any): LegalDocumentAdministrationQueriesAdminLegalDocumentList {
    return LegalDocumentAdministrationQueriesAdminLegalDocumentListFromJSONTyped(json, false);
}

export function LegalDocumentAdministrationQueriesAdminLegalDocumentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalDocumentAdministrationQueriesAdminLegalDocumentList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'slug': json['slug'],
        'content': json['content'],
    };
}

export function LegalDocumentAdministrationQueriesAdminLegalDocumentListToJSON(value?: LegalDocumentAdministrationQueriesAdminLegalDocumentList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'slug': value.slug,
        'content': value.content,
    };
}

