/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveQueriesTeacherDetailsForCall
 */
export interface LiveQueriesTeacherDetailsForCall {
    /**
     * 
     * @type {number}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    metadataId?: number;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    avatar1X?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    avatar2X?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    avatar3X?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveQueriesTeacherDetailsForCall
     */
    avatar4X?: string | null;
}

/**
 * Check if a given object implements the LiveQueriesTeacherDetailsForCall interface.
 */
export function instanceOfLiveQueriesTeacherDetailsForCall(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LiveQueriesTeacherDetailsForCallFromJSON(json: any): LiveQueriesTeacherDetailsForCall {
    return LiveQueriesTeacherDetailsForCallFromJSONTyped(json, false);
}

export function LiveQueriesTeacherDetailsForCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveQueriesTeacherDetailsForCall {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'metadataId': !exists(json, 'metadataId') ? undefined : json['metadataId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'avatar1X': !exists(json, 'avatar1X') ? undefined : json['avatar1X'],
        'avatar2X': !exists(json, 'avatar2X') ? undefined : json['avatar2X'],
        'avatar3X': !exists(json, 'avatar3X') ? undefined : json['avatar3X'],
        'avatar4X': !exists(json, 'avatar4X') ? undefined : json['avatar4X'],
    };
}

export function LiveQueriesTeacherDetailsForCallToJSON(value?: LiveQueriesTeacherDetailsForCall | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'metadataId': value.metadataId,
        'name': value.name,
        'avatar1X': value.avatar1X,
        'avatar2X': value.avatar2X,
        'avatar3X': value.avatar3X,
        'avatar4X': value.avatar4X,
    };
}

