/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AdvancerModelsSubscriptionSubscriptionDayOptionModel } from './AdvancerModelsSubscriptionSubscriptionDayOptionModel';
import {
    AdvancerModelsSubscriptionSubscriptionDayOptionModelFromJSON,
    AdvancerModelsSubscriptionSubscriptionDayOptionModelFromJSONTyped,
    AdvancerModelsSubscriptionSubscriptionDayOptionModelToJSON,
} from './AdvancerModelsSubscriptionSubscriptionDayOptionModel';
import type { AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel } from './AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel';
import {
    AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelFromJSON,
    AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelFromJSONTyped,
    AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelToJSON,
} from './AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel';
import type { AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel } from './AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel';
import {
    AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModelFromJSON,
    AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModelFromJSONTyped,
    AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModelToJSON,
} from './AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel';

/**
 * 
 * @export
 * @interface PaymentQueriesListDropDownSubscriptionOptionsQueryResult
 */
export interface PaymentQueriesListDropDownSubscriptionOptionsQueryResult {
    /**
     * Her dakika başına ücret
     * @type {number}
     * @memberof PaymentQueriesListDropDownSubscriptionOptionsQueryResult
     */
    pricePerMinute: number;
    /**
     * Paketlerin haftada kaç gün olabileceklerinin listesi
     * @type {Array<AdvancerModelsSubscriptionSubscriptionDayOptionModel>}
     * @memberof PaymentQueriesListDropDownSubscriptionOptionsQueryResult
     */
    dayPossibilities: Array<AdvancerModelsSubscriptionSubscriptionDayOptionModel>;
    /**
     * Aboneliğin günde kaç dakika olabileceği
     * @type {Array<AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel>}
     * @memberof PaymentQueriesListDropDownSubscriptionOptionsQueryResult
     */
    minutesPerDayPossibilities: Array<AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModel>;
    /**
     * Ödeme süre seçeneklerininin listesi.
     * @type {Array<AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel>}
     * @memberof PaymentQueriesListDropDownSubscriptionOptionsQueryResult
     */
    packageDurationPossibilities?: Array<AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModel> | null;
}

/**
 * Check if a given object implements the PaymentQueriesListDropDownSubscriptionOptionsQueryResult interface.
 */
export function instanceOfPaymentQueriesListDropDownSubscriptionOptionsQueryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pricePerMinute" in value;
    isInstance = isInstance && "dayPossibilities" in value;
    isInstance = isInstance && "minutesPerDayPossibilities" in value;

    return isInstance;
}

export function PaymentQueriesListDropDownSubscriptionOptionsQueryResultFromJSON(json: any): PaymentQueriesListDropDownSubscriptionOptionsQueryResult {
    return PaymentQueriesListDropDownSubscriptionOptionsQueryResultFromJSONTyped(json, false);
}

export function PaymentQueriesListDropDownSubscriptionOptionsQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentQueriesListDropDownSubscriptionOptionsQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pricePerMinute': json['pricePerMinute'],
        'dayPossibilities': ((json['dayPossibilities'] as Array<any>).map(AdvancerModelsSubscriptionSubscriptionDayOptionModelFromJSON)),
        'minutesPerDayPossibilities': ((json['minutesPerDayPossibilities'] as Array<any>).map(AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelFromJSON)),
        'packageDurationPossibilities': !exists(json, 'packageDurationPossibilities') ? undefined : (json['packageDurationPossibilities'] === null ? null : (json['packageDurationPossibilities'] as Array<any>).map(AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModelFromJSON)),
    };
}

export function PaymentQueriesListDropDownSubscriptionOptionsQueryResultToJSON(value?: PaymentQueriesListDropDownSubscriptionOptionsQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pricePerMinute': value.pricePerMinute,
        'dayPossibilities': ((value.dayPossibilities as Array<any>).map(AdvancerModelsSubscriptionSubscriptionDayOptionModelToJSON)),
        'minutesPerDayPossibilities': ((value.minutesPerDayPossibilities as Array<any>).map(AdvancerModelsSubscriptionSubscriptionMinutesPerDayOptionModelToJSON)),
        'packageDurationPossibilities': value.packageDurationPossibilities === undefined ? undefined : (value.packageDurationPossibilities === null ? null : (value.packageDurationPossibilities as Array<any>).map(AdvancerModelsSubscriptionSubscriptionPackageDurationOptionModelToJSON)),
    };
}

