/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PromotionAdministrationQueriesDiscountsListItem } from './PromotionAdministrationQueriesDiscountsListItem';
import {
    PromotionAdministrationQueriesDiscountsListItemFromJSON,
    PromotionAdministrationQueriesDiscountsListItemFromJSONTyped,
    PromotionAdministrationQueriesDiscountsListItemToJSON,
} from './PromotionAdministrationQueriesDiscountsListItem';
import type { PromotionAdministrationQueriesListDiscountsPagination } from './PromotionAdministrationQueriesListDiscountsPagination';
import {
    PromotionAdministrationQueriesListDiscountsPaginationFromJSON,
    PromotionAdministrationQueriesListDiscountsPaginationFromJSONTyped,
    PromotionAdministrationQueriesListDiscountsPaginationToJSON,
} from './PromotionAdministrationQueriesListDiscountsPagination';

/**
 * 
 * @export
 * @interface PromotionAdministrationQueriesListDiscountsQueryResult
 */
export interface PromotionAdministrationQueriesListDiscountsQueryResult {
    /**
     * 
     * @type {PromotionAdministrationQueriesListDiscountsPagination}
     * @memberof PromotionAdministrationQueriesListDiscountsQueryResult
     */
    pagination: PromotionAdministrationQueriesListDiscountsPagination;
    /**
     * 
     * @type {Array<PromotionAdministrationQueriesDiscountsListItem>}
     * @memberof PromotionAdministrationQueriesListDiscountsQueryResult
     */
    discountsList: Array<PromotionAdministrationQueriesDiscountsListItem>;
}

/**
 * Check if a given object implements the PromotionAdministrationQueriesListDiscountsQueryResult interface.
 */
export function instanceOfPromotionAdministrationQueriesListDiscountsQueryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pagination" in value;
    isInstance = isInstance && "discountsList" in value;

    return isInstance;
}

export function PromotionAdministrationQueriesListDiscountsQueryResultFromJSON(json: any): PromotionAdministrationQueriesListDiscountsQueryResult {
    return PromotionAdministrationQueriesListDiscountsQueryResultFromJSONTyped(json, false);
}

export function PromotionAdministrationQueriesListDiscountsQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotionAdministrationQueriesListDiscountsQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': PromotionAdministrationQueriesListDiscountsPaginationFromJSON(json['pagination']),
        'discountsList': ((json['discountsList'] as Array<any>).map(PromotionAdministrationQueriesDiscountsListItemFromJSON)),
    };
}

export function PromotionAdministrationQueriesListDiscountsQueryResultToJSON(value?: PromotionAdministrationQueriesListDiscountsQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pagination': PromotionAdministrationQueriesListDiscountsPaginationToJSON(value.pagination),
        'discountsList': ((value.discountsList as Array<any>).map(PromotionAdministrationQueriesDiscountsListItemToJSON)),
    };
}

