/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AdvancerCommonReferralStatus } from './AdvancerCommonReferralStatus';
import {
    AdvancerCommonReferralStatusFromJSON,
    AdvancerCommonReferralStatusFromJSONTyped,
    AdvancerCommonReferralStatusToJSON,
} from './AdvancerCommonReferralStatus';

/**
 * 
 * @export
 * @interface ReferralQueriesReferralDetails
 */
export interface ReferralQueriesReferralDetails {
    /**
     * 
     * @type {number}
     * @memberof ReferralQueriesReferralDetails
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ReferralQueriesReferralDetails
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReferralQueriesReferralDetails
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReferralQueriesReferralDetails
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ReferralQueriesReferralDetails
     */
    discount?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ReferralQueriesReferralDetails
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ReferralQueriesReferralDetails
     */
    endDate?: Date | null;
    /**
     * 
     * @type {AdvancerCommonReferralStatus}
     * @memberof ReferralQueriesReferralDetails
     */
    status?: AdvancerCommonReferralStatus;
    /**
     * 
     * @type {number}
     * @memberof ReferralQueriesReferralDetails
     */
    studentLimit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ReferralQueriesReferralDetails
     */
    availedLimit?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ReferralQueriesReferralDetails
     */
    isDeleted?: boolean | null;
}

/**
 * Check if a given object implements the ReferralQueriesReferralDetails interface.
 */
export function instanceOfReferralQueriesReferralDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferralQueriesReferralDetailsFromJSON(json: any): ReferralQueriesReferralDetails {
    return ReferralQueriesReferralDetailsFromJSONTyped(json, false);
}

export function ReferralQueriesReferralDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralQueriesReferralDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'discount': !exists(json, 'discount') ? undefined : json['discount'],
        'startDate': !exists(json, 'startDate') ? undefined : (json['startDate'] === null ? null : new Date(json['startDate'])),
        'endDate': !exists(json, 'endDate') ? undefined : (json['endDate'] === null ? null : new Date(json['endDate'])),
        'status': !exists(json, 'status') ? undefined : AdvancerCommonReferralStatusFromJSON(json['status']),
        'studentLimit': !exists(json, 'studentLimit') ? undefined : json['studentLimit'],
        'availedLimit': !exists(json, 'availedLimit') ? undefined : json['availedLimit'],
        'isDeleted': !exists(json, 'isDeleted') ? undefined : json['isDeleted'],
    };
}

export function ReferralQueriesReferralDetailsToJSON(value?: ReferralQueriesReferralDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'title': value.title,
        'description': value.description,
        'discount': value.discount,
        'startDate': value.startDate === undefined ? undefined : (value.startDate === null ? null : value.startDate.toISOString()),
        'endDate': value.endDate === undefined ? undefined : (value.endDate === null ? null : value.endDate.toISOString()),
        'status': AdvancerCommonReferralStatusToJSON(value.status),
        'studentLimit': value.studentLimit,
        'availedLimit': value.availedLimit,
        'isDeleted': value.isDeleted,
    };
}

