/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AdvancerCommonReferralStatus } from './AdvancerCommonReferralStatus';
import {
    AdvancerCommonReferralStatusFromJSON,
    AdvancerCommonReferralStatusFromJSONTyped,
    AdvancerCommonReferralStatusToJSON,
} from './AdvancerCommonReferralStatus';

/**
 * 
 * @export
 * @interface ReferralCommandsUpdateStatusCommand
 */
export interface ReferralCommandsUpdateStatusCommand {
    /**
     * 
     * @type {number}
     * @memberof ReferralCommandsUpdateStatusCommand
     */
    id?: number;
    /**
     * 
     * @type {AdvancerCommonReferralStatus}
     * @memberof ReferralCommandsUpdateStatusCommand
     */
    status?: AdvancerCommonReferralStatus;
}

/**
 * Check if a given object implements the ReferralCommandsUpdateStatusCommand interface.
 */
export function instanceOfReferralCommandsUpdateStatusCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferralCommandsUpdateStatusCommandFromJSON(json: any): ReferralCommandsUpdateStatusCommand {
    return ReferralCommandsUpdateStatusCommandFromJSONTyped(json, false);
}

export function ReferralCommandsUpdateStatusCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralCommandsUpdateStatusCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'status': !exists(json, 'status') ? undefined : AdvancerCommonReferralStatusFromJSON(json['status']),
    };
}

export function ReferralCommandsUpdateStatusCommandToJSON(value?: ReferralCommandsUpdateStatusCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': AdvancerCommonReferralStatusToJSON(value.status),
    };
}

