/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentCreditQueriesListStudentCredit
 */
export interface StudentCreditQueriesListStudentCredit {
    /**
     * 
     * @type {number}
     * @memberof StudentCreditQueriesListStudentCredit
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof StudentCreditQueriesListStudentCredit
     */
    recordsPerPage: number;
    /**
     * 
     * @type {number}
     * @memberof StudentCreditQueriesListStudentCredit
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof StudentCreditQueriesListStudentCredit
     */
    totalRecords: number;
}

/**
 * Check if a given object implements the StudentCreditQueriesListStudentCredit interface.
 */
export function instanceOfStudentCreditQueriesListStudentCredit(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "recordsPerPage" in value;
    isInstance = isInstance && "currentPage" in value;
    isInstance = isInstance && "totalRecords" in value;

    return isInstance;
}

export function StudentCreditQueriesListStudentCreditFromJSON(json: any): StudentCreditQueriesListStudentCredit {
    return StudentCreditQueriesListStudentCreditFromJSONTyped(json, false);
}

export function StudentCreditQueriesListStudentCreditFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentCreditQueriesListStudentCredit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'],
        'recordsPerPage': json['recordsPerPage'],
        'currentPage': json['currentPage'],
        'totalRecords': json['totalRecords'],
    };
}

export function StudentCreditQueriesListStudentCreditToJSON(value?: StudentCreditQueriesListStudentCredit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalPages': value.totalPages,
        'recordsPerPage': value.recordsPerPage,
        'currentPage': value.currentPage,
        'totalRecords': value.totalRecords,
    };
}

