/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StudentCommandsCreatedPhotoInfo } from './StudentCommandsCreatedPhotoInfo';
import {
    StudentCommandsCreatedPhotoInfoFromJSON,
    StudentCommandsCreatedPhotoInfoFromJSONTyped,
    StudentCommandsCreatedPhotoInfoToJSON,
} from './StudentCommandsCreatedPhotoInfo';

/**
 * 
 * @export
 * @interface StudentCommandsUpdateProfilePhotoCommandResult
 */
export interface StudentCommandsUpdateProfilePhotoCommandResult {
    /**
     * 
     * @type {StudentCommandsCreatedPhotoInfo}
     * @memberof StudentCommandsUpdateProfilePhotoCommandResult
     */
    createdPhotoInfo: StudentCommandsCreatedPhotoInfo;
}

/**
 * Check if a given object implements the StudentCommandsUpdateProfilePhotoCommandResult interface.
 */
export function instanceOfStudentCommandsUpdateProfilePhotoCommandResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdPhotoInfo" in value;

    return isInstance;
}

export function StudentCommandsUpdateProfilePhotoCommandResultFromJSON(json: any): StudentCommandsUpdateProfilePhotoCommandResult {
    return StudentCommandsUpdateProfilePhotoCommandResultFromJSONTyped(json, false);
}

export function StudentCommandsUpdateProfilePhotoCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentCommandsUpdateProfilePhotoCommandResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdPhotoInfo': StudentCommandsCreatedPhotoInfoFromJSON(json['createdPhotoInfo']),
    };
}

export function StudentCommandsUpdateProfilePhotoCommandResultToJSON(value?: StudentCommandsUpdateProfilePhotoCommandResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdPhotoInfo': StudentCommandsCreatedPhotoInfoToJSON(value.createdPhotoInfo),
    };
}

