/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StudentQueriesExportedAccountInfo } from './StudentQueriesExportedAccountInfo';
import {
    StudentQueriesExportedAccountInfoFromJSON,
    StudentQueriesExportedAccountInfoFromJSONTyped,
    StudentQueriesExportedAccountInfoToJSON,
} from './StudentQueriesExportedAccountInfo';
import type { StudentQueriesListMyExportsPagination } from './StudentQueriesListMyExportsPagination';
import {
    StudentQueriesListMyExportsPaginationFromJSON,
    StudentQueriesListMyExportsPaginationFromJSONTyped,
    StudentQueriesListMyExportsPaginationToJSON,
} from './StudentQueriesListMyExportsPagination';

/**
 * 
 * @export
 * @interface StudentQueriesListMyExportsQueryResult
 */
export interface StudentQueriesListMyExportsQueryResult {
    /**
     * 
     * @type {StudentQueriesListMyExportsPagination}
     * @memberof StudentQueriesListMyExportsQueryResult
     */
    listMyExportsPagination: StudentQueriesListMyExportsPagination;
    /**
     * 
     * @type {Array<StudentQueriesExportedAccountInfo>}
     * @memberof StudentQueriesListMyExportsQueryResult
     */
    exportedAccountInfo: Array<StudentQueriesExportedAccountInfo>;
}

/**
 * Check if a given object implements the StudentQueriesListMyExportsQueryResult interface.
 */
export function instanceOfStudentQueriesListMyExportsQueryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "listMyExportsPagination" in value;
    isInstance = isInstance && "exportedAccountInfo" in value;

    return isInstance;
}

export function StudentQueriesListMyExportsQueryResultFromJSON(json: any): StudentQueriesListMyExportsQueryResult {
    return StudentQueriesListMyExportsQueryResultFromJSONTyped(json, false);
}

export function StudentQueriesListMyExportsQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentQueriesListMyExportsQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listMyExportsPagination': StudentQueriesListMyExportsPaginationFromJSON(json['listMyExportsPagination']),
        'exportedAccountInfo': ((json['exportedAccountInfo'] as Array<any>).map(StudentQueriesExportedAccountInfoFromJSON)),
    };
}

export function StudentQueriesListMyExportsQueryResultToJSON(value?: StudentQueriesListMyExportsQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listMyExportsPagination': StudentQueriesListMyExportsPaginationToJSON(value.listMyExportsPagination),
        'exportedAccountInfo': ((value.exportedAccountInfo as Array<any>).map(StudentQueriesExportedAccountInfoToJSON)),
    };
}

