/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentCreditCommandsCreateCommand
 */
export interface StudentCreditCommandsCreateCommand {
    /**
     * 
     * @type {number}
     * @memberof StudentCreditCommandsCreateCommand
     */
    studentMetadataId?: number;
    /**
     * 
     * @type {Date}
     * @memberof StudentCreditCommandsCreateCommand
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof StudentCreditCommandsCreateCommand
     */
    endDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof StudentCreditCommandsCreateCommand
     */
    earnedCredits?: number;
    /**
     * 
     * @type {number}
     * @memberof StudentCreditCommandsCreateCommand
     */
    remainingCredits?: number;
    /**
     * 
     * @type {number}
     * @memberof StudentCreditCommandsCreateCommand
     */
    spentCredits?: number;
}

/**
 * Check if a given object implements the StudentCreditCommandsCreateCommand interface.
 */
export function instanceOfStudentCreditCommandsCreateCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StudentCreditCommandsCreateCommandFromJSON(json: any): StudentCreditCommandsCreateCommand {
    return StudentCreditCommandsCreateCommandFromJSONTyped(json, false);
}

export function StudentCreditCommandsCreateCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentCreditCommandsCreateCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'studentMetadataId': !exists(json, 'studentMetadataId') ? undefined : json['studentMetadataId'],
        'startDate': !exists(json, 'startDate') ? undefined : (new Date(json['startDate'])),
        'endDate': !exists(json, 'endDate') ? undefined : (new Date(json['endDate'])),
        'earnedCredits': !exists(json, 'earnedCredits') ? undefined : json['earnedCredits'],
        'remainingCredits': !exists(json, 'remainingCredits') ? undefined : json['remainingCredits'],
        'spentCredits': !exists(json, 'spentCredits') ? undefined : json['spentCredits'],
    };
}

export function StudentCreditCommandsCreateCommandToJSON(value?: StudentCreditCommandsCreateCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'studentMetadataId': value.studentMetadataId,
        'startDate': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
        'endDate': value.endDate === undefined ? undefined : (value.endDate.toISOString()),
        'earnedCredits': value.earnedCredits,
        'remainingCredits': value.remainingCredits,
        'spentCredits': value.spentCredits,
    };
}

