/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StudentAdministrationQueriesStudentsListItem } from './StudentAdministrationQueriesStudentsListItem';
import {
    StudentAdministrationQueriesStudentsListItemFromJSON,
    StudentAdministrationQueriesStudentsListItemFromJSONTyped,
    StudentAdministrationQueriesStudentsListItemToJSON,
} from './StudentAdministrationQueriesStudentsListItem';
import type { StudentAdministrationQueriesStudentsPagination } from './StudentAdministrationQueriesStudentsPagination';
import {
    StudentAdministrationQueriesStudentsPaginationFromJSON,
    StudentAdministrationQueriesStudentsPaginationFromJSONTyped,
    StudentAdministrationQueriesStudentsPaginationToJSON,
} from './StudentAdministrationQueriesStudentsPagination';

/**
 * 
 * @export
 * @interface StudentAdministrationQueriesListQueryResult
 */
export interface StudentAdministrationQueriesListQueryResult {
    /**
     * 
     * @type {StudentAdministrationQueriesStudentsPagination}
     * @memberof StudentAdministrationQueriesListQueryResult
     */
    studentsPagination: StudentAdministrationQueriesStudentsPagination;
    /**
     * 
     * @type {Array<StudentAdministrationQueriesStudentsListItem>}
     * @memberof StudentAdministrationQueriesListQueryResult
     */
    students: Array<StudentAdministrationQueriesStudentsListItem>;
}

/**
 * Check if a given object implements the StudentAdministrationQueriesListQueryResult interface.
 */
export function instanceOfStudentAdministrationQueriesListQueryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "studentsPagination" in value;
    isInstance = isInstance && "students" in value;

    return isInstance;
}

export function StudentAdministrationQueriesListQueryResultFromJSON(json: any): StudentAdministrationQueriesListQueryResult {
    return StudentAdministrationQueriesListQueryResultFromJSONTyped(json, false);
}

export function StudentAdministrationQueriesListQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentAdministrationQueriesListQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'studentsPagination': StudentAdministrationQueriesStudentsPaginationFromJSON(json['studentsPagination']),
        'students': ((json['students'] as Array<any>).map(StudentAdministrationQueriesStudentsListItemFromJSON)),
    };
}

export function StudentAdministrationQueriesListQueryResultToJSON(value?: StudentAdministrationQueriesListQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'studentsPagination': StudentAdministrationQueriesStudentsPaginationToJSON(value.studentsPagination),
        'students': ((value.students as Array<any>).map(StudentAdministrationQueriesStudentsListItemToJSON)),
    };
}

