/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentQueriesExportedAccountInfo
 */
export interface StudentQueriesExportedAccountInfo {
    /**
     * 
     * @type {string}
     * @memberof StudentQueriesExportedAccountInfo
     */
    exportId: string;
    /**
     * 
     * @type {Date}
     * @memberof StudentQueriesExportedAccountInfo
     */
    createdAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof StudentQueriesExportedAccountInfo
     */
    isFileReady: boolean;
    /**
     * 
     * @type {string}
     * @memberof StudentQueriesExportedAccountInfo
     */
    zippedFileUrl?: string | null;
}

/**
 * Check if a given object implements the StudentQueriesExportedAccountInfo interface.
 */
export function instanceOfStudentQueriesExportedAccountInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "exportId" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "isFileReady" in value;

    return isInstance;
}

export function StudentQueriesExportedAccountInfoFromJSON(json: any): StudentQueriesExportedAccountInfo {
    return StudentQueriesExportedAccountInfoFromJSONTyped(json, false);
}

export function StudentQueriesExportedAccountInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentQueriesExportedAccountInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exportId': json['exportId'],
        'createdAt': (new Date(json['createdAt'])),
        'isFileReady': json['isFileReady'],
        'zippedFileUrl': !exists(json, 'zippedFileUrl') ? undefined : json['zippedFileUrl'],
    };
}

export function StudentQueriesExportedAccountInfoToJSON(value?: StudentQueriesExportedAccountInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exportId': value.exportId,
        'createdAt': (value.createdAt.toISOString()),
        'isFileReady': value.isFileReady,
        'zippedFileUrl': value.zippedFileUrl,
    };
}

