/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentCommandsStartToExportMyAllInformationsCommandResult
 */
export interface StudentCommandsStartToExportMyAllInformationsCommandResult {
    /**
     * 
     * @type {string}
     * @memberof StudentCommandsStartToExportMyAllInformationsCommandResult
     */
    exportCaseId: string;
}

/**
 * Check if a given object implements the StudentCommandsStartToExportMyAllInformationsCommandResult interface.
 */
export function instanceOfStudentCommandsStartToExportMyAllInformationsCommandResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "exportCaseId" in value;

    return isInstance;
}

export function StudentCommandsStartToExportMyAllInformationsCommandResultFromJSON(json: any): StudentCommandsStartToExportMyAllInformationsCommandResult {
    return StudentCommandsStartToExportMyAllInformationsCommandResultFromJSONTyped(json, false);
}

export function StudentCommandsStartToExportMyAllInformationsCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentCommandsStartToExportMyAllInformationsCommandResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exportCaseId': json['exportCaseId'],
    };
}

export function StudentCommandsStartToExportMyAllInformationsCommandResultToJSON(value?: StudentCommandsStartToExportMyAllInformationsCommandResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exportCaseId': value.exportCaseId,
    };
}

