/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeacherQueriesListFavoriteTeachersPagination } from './TeacherQueriesListFavoriteTeachersPagination';
import {
    TeacherQueriesListFavoriteTeachersPaginationFromJSON,
    TeacherQueriesListFavoriteTeachersPaginationFromJSONTyped,
    TeacherQueriesListFavoriteTeachersPaginationToJSON,
} from './TeacherQueriesListFavoriteTeachersPagination';
import type { TeacherQueriesTeacherListItem } from './TeacherQueriesTeacherListItem';
import {
    TeacherQueriesTeacherListItemFromJSON,
    TeacherQueriesTeacherListItemFromJSONTyped,
    TeacherQueriesTeacherListItemToJSON,
} from './TeacherQueriesTeacherListItem';

/**
 * 
 * @export
 * @interface TeacherQueriesListMyFavoritesQueryResult
 */
export interface TeacherQueriesListMyFavoritesQueryResult {
    /**
     * 
     * @type {TeacherQueriesListFavoriteTeachersPagination}
     * @memberof TeacherQueriesListMyFavoritesQueryResult
     */
    pagination: TeacherQueriesListFavoriteTeachersPagination;
    /**
     * 
     * @type {Array<TeacherQueriesTeacherListItem>}
     * @memberof TeacherQueriesListMyFavoritesQueryResult
     */
    teachers: Array<TeacherQueriesTeacherListItem>;
}

/**
 * Check if a given object implements the TeacherQueriesListMyFavoritesQueryResult interface.
 */
export function instanceOfTeacherQueriesListMyFavoritesQueryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pagination" in value;
    isInstance = isInstance && "teachers" in value;

    return isInstance;
}

export function TeacherQueriesListMyFavoritesQueryResultFromJSON(json: any): TeacherQueriesListMyFavoritesQueryResult {
    return TeacherQueriesListMyFavoritesQueryResultFromJSONTyped(json, false);
}

export function TeacherQueriesListMyFavoritesQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherQueriesListMyFavoritesQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': TeacherQueriesListFavoriteTeachersPaginationFromJSON(json['pagination']),
        'teachers': ((json['teachers'] as Array<any>).map(TeacherQueriesTeacherListItemFromJSON)),
    };
}

export function TeacherQueriesListMyFavoritesQueryResultToJSON(value?: TeacherQueriesListMyFavoritesQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pagination': TeacherQueriesListFavoriteTeachersPaginationToJSON(value.pagination),
        'teachers': ((value.teachers as Array<any>).map(TeacherQueriesTeacherListItemToJSON)),
    };
}

