/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeacherAdministrationCommandsCreatedPhotoInfo } from './TeacherAdministrationCommandsCreatedPhotoInfo';
import {
    TeacherAdministrationCommandsCreatedPhotoInfoFromJSON,
    TeacherAdministrationCommandsCreatedPhotoInfoFromJSONTyped,
    TeacherAdministrationCommandsCreatedPhotoInfoToJSON,
} from './TeacherAdministrationCommandsCreatedPhotoInfo';

/**
 * 
 * @export
 * @interface TeacherAdministrationCommandsChangeProfilePictureCommandResult
 */
export interface TeacherAdministrationCommandsChangeProfilePictureCommandResult {
    /**
     * 
     * @type {TeacherAdministrationCommandsCreatedPhotoInfo}
     * @memberof TeacherAdministrationCommandsChangeProfilePictureCommandResult
     */
    createdPhotoInfo: TeacherAdministrationCommandsCreatedPhotoInfo;
}

/**
 * Check if a given object implements the TeacherAdministrationCommandsChangeProfilePictureCommandResult interface.
 */
export function instanceOfTeacherAdministrationCommandsChangeProfilePictureCommandResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdPhotoInfo" in value;

    return isInstance;
}

export function TeacherAdministrationCommandsChangeProfilePictureCommandResultFromJSON(json: any): TeacherAdministrationCommandsChangeProfilePictureCommandResult {
    return TeacherAdministrationCommandsChangeProfilePictureCommandResultFromJSONTyped(json, false);
}

export function TeacherAdministrationCommandsChangeProfilePictureCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherAdministrationCommandsChangeProfilePictureCommandResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdPhotoInfo': TeacherAdministrationCommandsCreatedPhotoInfoFromJSON(json['createdPhotoInfo']),
    };
}

export function TeacherAdministrationCommandsChangeProfilePictureCommandResultToJSON(value?: TeacherAdministrationCommandsChangeProfilePictureCommandResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdPhotoInfo': TeacherAdministrationCommandsCreatedPhotoInfoToJSON(value.createdPhotoInfo),
    };
}

