/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeacherQueriesAvailability
 */
export interface TeacherQueriesAvailability {
    /**
     * 
     * @type {Date}
     * @memberof TeacherQueriesAvailability
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TeacherQueriesAvailability
     */
    end?: Date;
    /**
     * 
     * @type {number}
     * @memberof TeacherQueriesAvailability
     */
    idOfBoundedAppointment?: number | null;
}

/**
 * Check if a given object implements the TeacherQueriesAvailability interface.
 */
export function instanceOfTeacherQueriesAvailability(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeacherQueriesAvailabilityFromJSON(json: any): TeacherQueriesAvailability {
    return TeacherQueriesAvailabilityFromJSONTyped(json, false);
}

export function TeacherQueriesAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherQueriesAvailability {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': !exists(json, 'start') ? undefined : (new Date(json['start'])),
        'end': !exists(json, 'end') ? undefined : (new Date(json['end'])),
        'idOfBoundedAppointment': !exists(json, 'idOfBoundedAppointment') ? undefined : json['idOfBoundedAppointment'],
    };
}

export function TeacherQueriesAvailabilityToJSON(value?: TeacherQueriesAvailability | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start === undefined ? undefined : (value.start.toISOString()),
        'end': value.end === undefined ? undefined : (value.end.toISOString()),
        'idOfBoundedAppointment': value.idOfBoundedAppointment,
    };
}

