/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeacherQueriesSpecalities
 */
export interface TeacherQueriesSpecalities {
    /**
     * Girilebilecek değerler:
     * KIND_AND_PATIENT,
     * FUN_AND_GREGARIOUS,
     * SCHOLARLY_AND_KNOWLEDGEABLE
     * @type {Array<string>}
     * @memberof TeacherQueriesSpecalities
     */
    teachingStyles: Array<string>;
    /**
     * Girilebilecek değerler:
     * PRONUNCIATION_LESSONS,
     * GRAMMAR_LESSONS,
     * LESSONS_WITH_MOVIES,
     * LESSONS_FOR_CHILDREN,
     * BUSINESS_ENGLISH,
     * UNIVERSITY_ENGLISH_PREPARATION,
     * EXAM,
     * TOEFL_PREPARATION,
     * IELTS_PREPARATION
     * @type {Array<string>}
     * @memberof TeacherQueriesSpecalities
     */
    lessonTypes: Array<string>;
    /**
     * Girilebilecek değerler:
     * BEGINNER,
     * INTERMEDIATE,
     * ADVANCED
     * @type {Array<string>}
     * @memberof TeacherQueriesSpecalities
     */
    languageLevel: Array<string>;
}

/**
 * Check if a given object implements the TeacherQueriesSpecalities interface.
 */
export function instanceOfTeacherQueriesSpecalities(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "teachingStyles" in value;
    isInstance = isInstance && "lessonTypes" in value;
    isInstance = isInstance && "languageLevel" in value;

    return isInstance;
}

export function TeacherQueriesSpecalitiesFromJSON(json: any): TeacherQueriesSpecalities {
    return TeacherQueriesSpecalitiesFromJSONTyped(json, false);
}

export function TeacherQueriesSpecalitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherQueriesSpecalities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teachingStyles': json['teachingStyles'],
        'lessonTypes': json['lessonTypes'],
        'languageLevel': json['languageLevel'],
    };
}

export function TeacherQueriesSpecalitiesToJSON(value?: TeacherQueriesSpecalities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teachingStyles': value.teachingStyles,
        'lessonTypes': value.lessonTypes,
        'languageLevel': value.languageLevel,
    };
}

