/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WordTutorialCategoryQueriesWordTutorial } from './WordTutorialCategoryQueriesWordTutorial';
import {
    WordTutorialCategoryQueriesWordTutorialFromJSON,
    WordTutorialCategoryQueriesWordTutorialFromJSONTyped,
    WordTutorialCategoryQueriesWordTutorialToJSON,
} from './WordTutorialCategoryQueriesWordTutorial';

/**
 * 
 * @export
 * @interface WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult
 */
export interface WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult {
    /**
     * 
     * @type {number}
     * @memberof WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult
     */
    categoryId: number;
    /**
     * 
     * @type {Array<WordTutorialCategoryQueriesWordTutorial>}
     * @memberof WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult
     */
    wordTutorials: Array<WordTutorialCategoryQueriesWordTutorial>;
}

/**
 * Check if a given object implements the WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult interface.
 */
export function instanceOfWordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "categoryId" in value;
    isInstance = isInstance && "wordTutorials" in value;

    return isInstance;
}

export function WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResultFromJSON(json: any): WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult {
    return WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResultFromJSONTyped(json, false);
}

export function WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'],
        'wordTutorials': ((json['wordTutorials'] as Array<any>).map(WordTutorialCategoryQueriesWordTutorialFromJSON)),
    };
}

export function WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResultToJSON(value?: WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categoryId': value.categoryId,
        'wordTutorials': ((value.wordTutorials as Array<any>).map(WordTutorialCategoryQueriesWordTutorialToJSON)),
    };
}

