/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordTutorialCategoryQueriesSearchWordTutorialsPagination
 */
export interface WordTutorialCategoryQueriesSearchWordTutorialsPagination {
    /**
     * 
     * @type {boolean}
     * @memberof WordTutorialCategoryQueriesSearchWordTutorialsPagination
     */
    isNextPageAvailable: boolean;
    /**
     * 
     * @type {number}
     * @memberof WordTutorialCategoryQueriesSearchWordTutorialsPagination
     */
    lastId?: number | null;
}

/**
 * Check if a given object implements the WordTutorialCategoryQueriesSearchWordTutorialsPagination interface.
 */
export function instanceOfWordTutorialCategoryQueriesSearchWordTutorialsPagination(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isNextPageAvailable" in value;

    return isInstance;
}

export function WordTutorialCategoryQueriesSearchWordTutorialsPaginationFromJSON(json: any): WordTutorialCategoryQueriesSearchWordTutorialsPagination {
    return WordTutorialCategoryQueriesSearchWordTutorialsPaginationFromJSONTyped(json, false);
}

export function WordTutorialCategoryQueriesSearchWordTutorialsPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordTutorialCategoryQueriesSearchWordTutorialsPagination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isNextPageAvailable': json['isNextPageAvailable'],
        'lastId': !exists(json, 'lastId') ? undefined : json['lastId'],
    };
}

export function WordTutorialCategoryQueriesSearchWordTutorialsPaginationToJSON(value?: WordTutorialCategoryQueriesSearchWordTutorialsPagination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isNextPageAvailable': value.isNextPageAvailable,
        'lastId': value.lastId,
    };
}

