/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WordTutorialQueriesWordTutorialSubtitle } from './WordTutorialQueriesWordTutorialSubtitle';
import {
    WordTutorialQueriesWordTutorialSubtitleFromJSON,
    WordTutorialQueriesWordTutorialSubtitleFromJSONTyped,
    WordTutorialQueriesWordTutorialSubtitleToJSON,
} from './WordTutorialQueriesWordTutorialSubtitle';
import type { WordTutorialQueriesWordTutorialTranslation } from './WordTutorialQueriesWordTutorialTranslation';
import {
    WordTutorialQueriesWordTutorialTranslationFromJSON,
    WordTutorialQueriesWordTutorialTranslationFromJSONTyped,
    WordTutorialQueriesWordTutorialTranslationToJSON,
} from './WordTutorialQueriesWordTutorialTranslation';

/**
 * 
 * @export
 * @interface WordTutorialQueriesFavoriteWordTutorial
 */
export interface WordTutorialQueriesFavoriteWordTutorial {
    /**
     * 
     * @type {number}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    wordTutorialId: number;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    slug: string;
    /**
     * 
     * @type {boolean}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    isFavorited: boolean;
    /**
     * 
     * @type {number}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    wordTutorialCategoryId: number;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    wordTutorialCategorySlug: string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    coverImage1X: string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    coverImage2X: string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    coverImage3X: string;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    coverImage4X: string;
    /**
     * 
     * @type {Array<WordTutorialQueriesWordTutorialTranslation>}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    translations: Array<WordTutorialQueriesWordTutorialTranslation>;
    /**
     * 
     * @type {Array<WordTutorialQueriesWordTutorialSubtitle>}
     * @memberof WordTutorialQueriesFavoriteWordTutorial
     */
    subtitles: Array<WordTutorialQueriesWordTutorialSubtitle>;
}

/**
 * Check if a given object implements the WordTutorialQueriesFavoriteWordTutorial interface.
 */
export function instanceOfWordTutorialQueriesFavoriteWordTutorial(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "wordTutorialId" in value;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "isFavorited" in value;
    isInstance = isInstance && "wordTutorialCategoryId" in value;
    isInstance = isInstance && "wordTutorialCategorySlug" in value;
    isInstance = isInstance && "coverImage1X" in value;
    isInstance = isInstance && "coverImage2X" in value;
    isInstance = isInstance && "coverImage3X" in value;
    isInstance = isInstance && "coverImage4X" in value;
    isInstance = isInstance && "translations" in value;
    isInstance = isInstance && "subtitles" in value;

    return isInstance;
}

export function WordTutorialQueriesFavoriteWordTutorialFromJSON(json: any): WordTutorialQueriesFavoriteWordTutorial {
    return WordTutorialQueriesFavoriteWordTutorialFromJSONTyped(json, false);
}

export function WordTutorialQueriesFavoriteWordTutorialFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordTutorialQueriesFavoriteWordTutorial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'wordTutorialId': json['wordTutorialId'],
        'slug': json['slug'],
        'isFavorited': json['isFavorited'],
        'wordTutorialCategoryId': json['wordTutorialCategoryId'],
        'wordTutorialCategorySlug': json['wordTutorialCategorySlug'],
        'coverImage1X': json['coverImage1X'],
        'coverImage2X': json['coverImage2X'],
        'coverImage3X': json['coverImage3X'],
        'coverImage4X': json['coverImage4X'],
        'translations': ((json['translations'] as Array<any>).map(WordTutorialQueriesWordTutorialTranslationFromJSON)),
        'subtitles': ((json['subtitles'] as Array<any>).map(WordTutorialQueriesWordTutorialSubtitleFromJSON)),
    };
}

export function WordTutorialQueriesFavoriteWordTutorialToJSON(value?: WordTutorialQueriesFavoriteWordTutorial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'wordTutorialId': value.wordTutorialId,
        'slug': value.slug,
        'isFavorited': value.isFavorited,
        'wordTutorialCategoryId': value.wordTutorialCategoryId,
        'wordTutorialCategorySlug': value.wordTutorialCategorySlug,
        'coverImage1X': value.coverImage1X,
        'coverImage2X': value.coverImage2X,
        'coverImage3X': value.coverImage3X,
        'coverImage4X': value.coverImage4X,
        'translations': ((value.translations as Array<any>).map(WordTutorialQueriesWordTutorialTranslationToJSON)),
        'subtitles': ((value.subtitles as Array<any>).map(WordTutorialQueriesWordTutorialSubtitleToJSON)),
    };
}

