/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordTutorialQueriesSubtitleContent
 */
export interface WordTutorialQueriesSubtitleContent {
    /**
     * 
     * @type {number}
     * @memberof WordTutorialQueriesSubtitleContent
     */
    contentId: number;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialQueriesSubtitleContent
     */
    content: string;
}

/**
 * Check if a given object implements the WordTutorialQueriesSubtitleContent interface.
 */
export function instanceOfWordTutorialQueriesSubtitleContent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contentId" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function WordTutorialQueriesSubtitleContentFromJSON(json: any): WordTutorialQueriesSubtitleContent {
    return WordTutorialQueriesSubtitleContentFromJSONTyped(json, false);
}

export function WordTutorialQueriesSubtitleContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordTutorialQueriesSubtitleContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentId': json['contentId'],
        'content': json['content'],
    };
}

export function WordTutorialQueriesSubtitleContentToJSON(value?: WordTutorialQueriesSubtitleContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contentId': value.contentId,
        'content': value.content,
    };
}

