/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AdvancerModelsWordTutorialCategoryWordTutorialCategoryModel } from './AdvancerModelsWordTutorialCategoryWordTutorialCategoryModel';
import {
    AdvancerModelsWordTutorialCategoryWordTutorialCategoryModelFromJSON,
    AdvancerModelsWordTutorialCategoryWordTutorialCategoryModelFromJSONTyped,
    AdvancerModelsWordTutorialCategoryWordTutorialCategoryModelToJSON,
} from './AdvancerModelsWordTutorialCategoryWordTutorialCategoryModel';
import type { WordTutorialCategoryQueriesWordTutorialDetails } from './WordTutorialCategoryQueriesWordTutorialDetails';
import {
    WordTutorialCategoryQueriesWordTutorialDetailsFromJSON,
    WordTutorialCategoryQueriesWordTutorialDetailsFromJSONTyped,
    WordTutorialCategoryQueriesWordTutorialDetailsToJSON,
} from './WordTutorialCategoryQueriesWordTutorialDetails';

/**
 * 
 * @export
 * @interface WordTutorialCategoryQueriesGetDetailsQueryResult
 */
export interface WordTutorialCategoryQueriesGetDetailsQueryResult {
    /**
     * 
     * @type {number}
     * @memberof WordTutorialCategoryQueriesGetDetailsQueryResult
     */
    totalWordTutorialsInCategory: number;
    /**
     * 
     * @type {number}
     * @memberof WordTutorialCategoryQueriesGetDetailsQueryResult
     */
    completedWordTutorialsInCurrentCategory: number;
    /**
     * 
     * @type {WordTutorialCategoryQueriesWordTutorialDetails}
     * @memberof WordTutorialCategoryQueriesGetDetailsQueryResult
     */
    previousWordTutorial?: WordTutorialCategoryQueriesWordTutorialDetails;
    /**
     * 
     * @type {WordTutorialCategoryQueriesWordTutorialDetails}
     * @memberof WordTutorialCategoryQueriesGetDetailsQueryResult
     */
    currentWordTutorial: WordTutorialCategoryQueriesWordTutorialDetails;
    /**
     * 
     * @type {WordTutorialCategoryQueriesWordTutorialDetails}
     * @memberof WordTutorialCategoryQueriesGetDetailsQueryResult
     */
    nextWordTutorial?: WordTutorialCategoryQueriesWordTutorialDetails;
    /**
     * 
     * @type {AdvancerModelsWordTutorialCategoryWordTutorialCategoryModel}
     * @memberof WordTutorialCategoryQueriesGetDetailsQueryResult
     */
    categories?: AdvancerModelsWordTutorialCategoryWordTutorialCategoryModel;
}

/**
 * Check if a given object implements the WordTutorialCategoryQueriesGetDetailsQueryResult interface.
 */
export function instanceOfWordTutorialCategoryQueriesGetDetailsQueryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalWordTutorialsInCategory" in value;
    isInstance = isInstance && "completedWordTutorialsInCurrentCategory" in value;
    isInstance = isInstance && "currentWordTutorial" in value;

    return isInstance;
}

export function WordTutorialCategoryQueriesGetDetailsQueryResultFromJSON(json: any): WordTutorialCategoryQueriesGetDetailsQueryResult {
    return WordTutorialCategoryQueriesGetDetailsQueryResultFromJSONTyped(json, false);
}

export function WordTutorialCategoryQueriesGetDetailsQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordTutorialCategoryQueriesGetDetailsQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalWordTutorialsInCategory': json['totalWordTutorialsInCategory'],
        'completedWordTutorialsInCurrentCategory': json['completedWordTutorialsInCurrentCategory'],
        'previousWordTutorial': !exists(json, 'previousWordTutorial') ? undefined : WordTutorialCategoryQueriesWordTutorialDetailsFromJSON(json['previousWordTutorial']),
        'currentWordTutorial': WordTutorialCategoryQueriesWordTutorialDetailsFromJSON(json['currentWordTutorial']),
        'nextWordTutorial': !exists(json, 'nextWordTutorial') ? undefined : WordTutorialCategoryQueriesWordTutorialDetailsFromJSON(json['nextWordTutorial']),
        'categories': !exists(json, 'categories') ? undefined : AdvancerModelsWordTutorialCategoryWordTutorialCategoryModelFromJSON(json['categories']),
    };
}

export function WordTutorialCategoryQueriesGetDetailsQueryResultToJSON(value?: WordTutorialCategoryQueriesGetDetailsQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalWordTutorialsInCategory': value.totalWordTutorialsInCategory,
        'completedWordTutorialsInCurrentCategory': value.completedWordTutorialsInCurrentCategory,
        'previousWordTutorial': WordTutorialCategoryQueriesWordTutorialDetailsToJSON(value.previousWordTutorial),
        'currentWordTutorial': WordTutorialCategoryQueriesWordTutorialDetailsToJSON(value.currentWordTutorial),
        'nextWordTutorial': WordTutorialCategoryQueriesWordTutorialDetailsToJSON(value.nextWordTutorial),
        'categories': AdvancerModelsWordTutorialCategoryWordTutorialCategoryModelToJSON(value.categories),
    };
}

