/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult
 */
export interface WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult {
    /**
     * 
     * @type {number}
     * @memberof WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult
     */
    subtitleId?: number;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult
     */
    subtitleFileId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult
     */
    lineContents?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult
     */
    url?: string | null;
}

/**
 * Check if a given object implements the WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult interface.
 */
export function instanceOfWordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResultFromJSON(json: any): WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult {
    return WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResultFromJSONTyped(json, false);
}

export function WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subtitleId': !exists(json, 'subtitleId') ? undefined : json['subtitleId'],
        'subtitleFileId': !exists(json, 'subtitleFileId') ? undefined : json['subtitleFileId'],
        'lineContents': !exists(json, 'lineContents') ? undefined : json['lineContents'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResultToJSON(value?: WordTutorialSubtitleAdministrationCommandsAddSubtitleToWordTutorialCommandResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subtitleId': value.subtitleId,
        'subtitleFileId': value.subtitleFileId,
        'lineContents': value.lineContents,
        'url': value.url,
    };
}

