/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordTutorialAdministrationCommandsPostWordTutorialTranslation
 */
export interface WordTutorialAdministrationCommandsPostWordTutorialTranslation {
    /**
     * 
     * @type {string}
     * @memberof WordTutorialAdministrationCommandsPostWordTutorialTranslation
     */
    languageCode: string;
    /**
     * 
     * @type {boolean}
     * @memberof WordTutorialAdministrationCommandsPostWordTutorialTranslation
     */
    isRtlLanguage: boolean;
    /**
     * 
     * @type {string}
     * @memberof WordTutorialAdministrationCommandsPostWordTutorialTranslation
     */
    content: string;
}

/**
 * Check if a given object implements the WordTutorialAdministrationCommandsPostWordTutorialTranslation interface.
 */
export function instanceOfWordTutorialAdministrationCommandsPostWordTutorialTranslation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "languageCode" in value;
    isInstance = isInstance && "isRtlLanguage" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function WordTutorialAdministrationCommandsPostWordTutorialTranslationFromJSON(json: any): WordTutorialAdministrationCommandsPostWordTutorialTranslation {
    return WordTutorialAdministrationCommandsPostWordTutorialTranslationFromJSONTyped(json, false);
}

export function WordTutorialAdministrationCommandsPostWordTutorialTranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordTutorialAdministrationCommandsPostWordTutorialTranslation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'languageCode': json['languageCode'],
        'isRtlLanguage': json['isRtlLanguage'],
        'content': json['content'],
    };
}

export function WordTutorialAdministrationCommandsPostWordTutorialTranslationToJSON(value?: WordTutorialAdministrationCommandsPostWordTutorialTranslation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'languageCode': value.languageCode,
        'isRtlLanguage': value.isRtlLanguage,
        'content': value.content,
    };
}

