/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WordTutorialAdministrationQueriesWordTutorialListItem } from './WordTutorialAdministrationQueriesWordTutorialListItem';
import {
    WordTutorialAdministrationQueriesWordTutorialListItemFromJSON,
    WordTutorialAdministrationQueriesWordTutorialListItemFromJSONTyped,
    WordTutorialAdministrationQueriesWordTutorialListItemToJSON,
} from './WordTutorialAdministrationQueriesWordTutorialListItem';

/**
 * 
 * @export
 * @interface WordTutorialAdministrationQueriesListQueryResult
 */
export interface WordTutorialAdministrationQueriesListQueryResult {
    /**
     * 
     * @type {Array<WordTutorialAdministrationQueriesWordTutorialListItem>}
     * @memberof WordTutorialAdministrationQueriesListQueryResult
     */
    wordTutorials: Array<WordTutorialAdministrationQueriesWordTutorialListItem>;
}

/**
 * Check if a given object implements the WordTutorialAdministrationQueriesListQueryResult interface.
 */
export function instanceOfWordTutorialAdministrationQueriesListQueryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "wordTutorials" in value;

    return isInstance;
}

export function WordTutorialAdministrationQueriesListQueryResultFromJSON(json: any): WordTutorialAdministrationQueriesListQueryResult {
    return WordTutorialAdministrationQueriesListQueryResultFromJSONTyped(json, false);
}

export function WordTutorialAdministrationQueriesListQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordTutorialAdministrationQueriesListQueryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'wordTutorials': ((json['wordTutorials'] as Array<any>).map(WordTutorialAdministrationQueriesWordTutorialListItemFromJSON)),
    };
}

export function WordTutorialAdministrationQueriesListQueryResultToJSON(value?: WordTutorialAdministrationQueriesListQueryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wordTutorials': ((value.wordTutorials as Array<any>).map(WordTutorialAdministrationQueriesWordTutorialListItemToJSON)),
    };
}

